// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/assets/asset_policy.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AssetPolicyStatus defines the lifecycle state of an asset policy.
type AssetPolicyStatus int32

const (
	// Unspecified is not a valid persisted policy state.
	AssetPolicyStatus_ASSET_POLICY_STATUS_UNSPECIFIED AssetPolicyStatus = 0
	// Active permits operations enabled by the policy flags.
	AssetPolicyStatus_ASSET_POLICY_STATUS_ACTIVE AssetPolicyStatus = 1
	// Paused blocks new deposits and trading while preserving withdrawals.
	AssetPolicyStatus_ASSET_POLICY_STATUS_PAUSED AssetPolicyStatus = 2
	// Retired permanently blocks new deposits and trading while preserving
	// withdrawals.
	AssetPolicyStatus_ASSET_POLICY_STATUS_RETIRED AssetPolicyStatus = 3
)

var AssetPolicyStatus_name = map[int32]string{
	0: "ASSET_POLICY_STATUS_UNSPECIFIED",
	1: "ASSET_POLICY_STATUS_ACTIVE",
	2: "ASSET_POLICY_STATUS_PAUSED",
	3: "ASSET_POLICY_STATUS_RETIRED",
}

var AssetPolicyStatus_value = map[string]int32{
	"ASSET_POLICY_STATUS_UNSPECIFIED": 0,
	"ASSET_POLICY_STATUS_ACTIVE":      1,
	"ASSET_POLICY_STATUS_PAUSED":      2,
	"ASSET_POLICY_STATUS_RETIRED":     3,
}

func (x AssetPolicyStatus) String() string {
	return proto.EnumName(AssetPolicyStatus_name, int32(x))
}

func (AssetPolicyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8ee371d5105d131, []int{0}
}

// AssetPolicy defines the mutable business permissions for an asset.
type AssetPolicy struct {
	// AssetId identifies the immutable Asset governed by this policy.
	AssetId uint32 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Status is the lifecycle state of the policy.
	Status AssetPolicyStatus `protobuf:"varint,2,opt,name=status,proto3,enum=dydxprotocol.assets.AssetPolicyStatus" json:"status,omitempty"`
	// DepositsEnabled permits new bank-to-funding deposits while active.
	DepositsEnabled bool `protobuf:"varint,3,opt,name=deposits_enabled,json=depositsEnabled,proto3" json:"deposits_enabled,omitempty"`
	// WithdrawalsEnabled permits funding-to-bank withdrawals.
	WithdrawalsEnabled bool `protobuf:"varint,4,opt,name=withdrawals_enabled,json=withdrawalsEnabled,proto3" json:"withdrawals_enabled,omitempty"`
	// SpotTradingEnabled permits spot transfers, orders, and fills while active.
	SpotTradingEnabled bool `protobuf:"varint,5,opt,name=spot_trading_enabled,json=spotTradingEnabled,proto3" json:"spot_trading_enabled,omitempty"`
	// PerpetualEnabled permits use by existing perpetual asset paths.
	PerpetualEnabled bool `protobuf:"varint,6,opt,name=perpetual_enabled,json=perpetualEnabled,proto3" json:"perpetual_enabled,omitempty"`
}

func (m *AssetPolicy) Reset()         { *m = AssetPolicy{} }
func (m *AssetPolicy) String() string { return proto.CompactTextString(m) }
func (*AssetPolicy) ProtoMessage()    {}
func (*AssetPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8ee371d5105d131, []int{0}
}
func (m *AssetPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetPolicy.Merge(m, src)
}
func (m *AssetPolicy) XXX_Size() int {
	return m.Size()
}
func (m *AssetPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_AssetPolicy proto.InternalMessageInfo

func (m *AssetPolicy) GetAssetId() uint32 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *AssetPolicy) GetStatus() AssetPolicyStatus {
	if m != nil {
		return m.Status
	}
	return AssetPolicyStatus_ASSET_POLICY_STATUS_UNSPECIFIED
}

func (m *AssetPolicy) GetDepositsEnabled() bool {
	if m != nil {
		return m.DepositsEnabled
	}
	return false
}

func (m *AssetPolicy) GetWithdrawalsEnabled() bool {
	if m != nil {
		return m.WithdrawalsEnabled
	}
	return false
}

func (m *AssetPolicy) GetSpotTradingEnabled() bool {
	if m != nil {
		return m.SpotTradingEnabled
	}
	return false
}

func (m *AssetPolicy) GetPerpetualEnabled() bool {
	if m != nil {
		return m.PerpetualEnabled
	}
	return false
}

func init() {
	proto.RegisterEnum("dydxprotocol.assets.AssetPolicyStatus", AssetPolicyStatus_name, AssetPolicyStatus_value)
	proto.RegisterType((*AssetPolicy)(nil), "dydxprotocol.assets.AssetPolicy")
}

func init() {
	proto.RegisterFile("dydxprotocol/assets/asset_policy.proto", fileDescriptor_f8ee371d5105d131)
}

var fileDescriptor_f8ee371d5105d131 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x33, 0xed, 0xbd, 0xbd, 0x65, 0x2e, 0x6a, 0x3a, 0x75, 0x51, 0x15, 0xd2, 0xa2, 0x50,
	0xaa, 0x62, 0x22, 0xea, 0xc2, 0x95, 0x10, 0xdb, 0x11, 0x02, 0xa2, 0x21, 0x49, 0x05, 0xdd, 0x84,
	0x69, 0x26, 0xb4, 0x81, 0xd8, 0x84, 0xcc, 0xd4, 0xb6, 0x6f, 0xe1, 0xd6, 0xb5, 0x2f, 0xe3, 0xb2,
	0x4b, 0x97, 0xd2, 0xbe, 0x88, 0x34, 0x69, 0x62, 0xc5, 0xba, 0x9a, 0x99, 0xff, 0xfb, 0xfe, 0x03,
	0x03, 0x07, 0xd6, 0xe9, 0x98, 0x8e, 0xc2, 0x28, 0xe0, 0x81, 0x13, 0xf8, 0x0a, 0x61, 0xcc, 0xe5,
	0x2c, 0x39, 0xec, 0x30, 0xf0, 0x3d, 0x67, 0x2c, 0xc7, 0x10, 0x95, 0x97, 0x3d, 0x39, 0xf1, 0x76,
	0x5f, 0x73, 0xf0, 0xbf, 0x3a, 0xbf, 0xea, 0xb1, 0x8a, 0xb6, 0x60, 0x31, 0xa9, 0x7a, 0xb4, 0x02,
	0x6a, 0xa0, 0xb1, 0x66, 0xfc, 0x8b, 0xdf, 0x1a, 0x45, 0x17, 0xb0, 0xc0, 0x38, 0xe1, 0x03, 0x56,
	0xc9, 0xd5, 0x40, 0x63, 0xfd, 0xa4, 0x2e, 0xaf, 0x18, 0x28, 0x2f, 0x0d, 0x33, 0x63, 0xdb, 0x58,
	0xb4, 0xd0, 0x3e, 0x14, 0xa9, 0x1b, 0x06, 0xcc, 0xe3, 0xcc, 0x76, 0xfb, 0xa4, 0xe3, 0xbb, 0xb4,
	0x92, 0xaf, 0x81, 0x46, 0xd1, 0xd8, 0x48, 0x73, 0x9c, 0xc4, 0x48, 0x81, 0xe5, 0xa1, 0xc7, 0x7b,
	0x34, 0x22, 0x43, 0xe2, 0x7f, 0xd9, 0x7f, 0x62, 0x1b, 0x2d, 0xa1, 0xb4, 0x70, 0x0c, 0x37, 0x59,
	0x18, 0x70, 0x9b, 0x47, 0x84, 0x7a, 0xfd, 0x6e, 0xd6, 0xf8, 0x9b, 0x34, 0xe6, 0xcc, 0x4a, 0x50,
	0xda, 0x38, 0x84, 0xa5, 0xd0, 0x8d, 0x42, 0x97, 0x0f, 0x88, 0x9f, 0xe9, 0x85, 0x58, 0x17, 0x33,
	0xb0, 0x90, 0x0f, 0x5e, 0x00, 0x2c, 0xfd, 0xf8, 0x18, 0xda, 0x83, 0x55, 0xd5, 0x34, 0xb1, 0x65,
	0xeb, 0xb7, 0xd7, 0x5a, 0xf3, 0xde, 0x36, 0x2d, 0xd5, 0x6a, 0x9b, 0x76, 0xfb, 0xc6, 0xd4, 0x71,
	0x53, 0xbb, 0xd2, 0x70, 0x4b, 0x14, 0x90, 0x04, 0xb7, 0x57, 0x49, 0x6a, 0xd3, 0xd2, 0xee, 0xb0,
	0x08, 0x7e, 0xe3, 0xba, 0xda, 0x36, 0x71, 0x4b, 0xcc, 0xa1, 0x2a, 0xdc, 0x59, 0xc5, 0x0d, 0x6c,
	0x69, 0x06, 0x6e, 0x89, 0xf9, 0x4b, 0xe3, 0x6d, 0x2a, 0x81, 0xc9, 0x54, 0x02, 0x1f, 0x53, 0x09,
	0x3c, 0xcf, 0x24, 0x61, 0x32, 0x93, 0x84, 0xf7, 0x99, 0x24, 0x3c, 0x9c, 0x77, 0x3d, 0xde, 0x1b,
	0x74, 0x64, 0x27, 0x78, 0x54, 0xbe, 0xed, 0xc8, 0xd3, 0xd9, 0x91, 0xd3, 0x23, 0x5e, 0x5f, 0xc9,
	0x92, 0x51, 0xba, 0x37, 0x7c, 0x1c, 0xba, 0xac, 0x53, 0x88, 0xc1, 0xe9, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x78, 0x6a, 0x26, 0x79, 0x5b, 0x02, 0x00, 0x00,
}

func (m *AssetPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PerpetualEnabled {
		i--
		if m.PerpetualEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.SpotTradingEnabled {
		i--
		if m.SpotTradingEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.WithdrawalsEnabled {
		i--
		if m.WithdrawalsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.DepositsEnabled {
		i--
		if m.DepositsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Status != 0 {
		i = encodeVarintAssetPolicy(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if m.AssetId != 0 {
		i = encodeVarintAssetPolicy(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAssetPolicy(dAtA []byte, offset int, v uint64) int {
	offset -= sovAssetPolicy(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AssetPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetId != 0 {
		n += 1 + sovAssetPolicy(uint64(m.AssetId))
	}
	if m.Status != 0 {
		n += 1 + sovAssetPolicy(uint64(m.Status))
	}
	if m.DepositsEnabled {
		n += 2
	}
	if m.WithdrawalsEnabled {
		n += 2
	}
	if m.SpotTradingEnabled {
		n += 2
	}
	if m.PerpetualEnabled {
		n += 2
	}
	return n
}

func sovAssetPolicy(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAssetPolicy(x uint64) (n int) {
	return sovAssetPolicy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AssetPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAssetPolicy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= AssetPolicyStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DepositsEnabled = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WithdrawalsEnabled = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpotTradingEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SpotTradingEnabled = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerpetualEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PerpetualEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAssetPolicy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAssetPolicy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAssetPolicy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAssetPolicy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAssetPolicy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAssetPolicy
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAssetPolicy
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAssetPolicy
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAssetPolicy        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAssetPolicy          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAssetPolicy = fmt.Errorf("proto: unexpected end of group")
)
