// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/feetiers/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_dydxprotocol_v4_chain_protocol_dtypes "github.com/dydxprotocol/v4-chain/protocol/dtypes"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryPerpetualFeeParamsRequest is a request type for the PerpetualFeeParams
// RPC method.
type QueryPerpetualFeeParamsRequest struct {
}

func (m *QueryPerpetualFeeParamsRequest) Reset()         { *m = QueryPerpetualFeeParamsRequest{} }
func (m *QueryPerpetualFeeParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPerpetualFeeParamsRequest) ProtoMessage()    {}
func (*QueryPerpetualFeeParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{0}
}
func (m *QueryPerpetualFeeParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPerpetualFeeParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPerpetualFeeParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPerpetualFeeParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPerpetualFeeParamsRequest.Merge(m, src)
}
func (m *QueryPerpetualFeeParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPerpetualFeeParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPerpetualFeeParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPerpetualFeeParamsRequest proto.InternalMessageInfo

// QueryPerpetualFeeParamsResponse is a response type for the PerpetualFeeParams
// RPC method.
type QueryPerpetualFeeParamsResponse struct {
	Params PerpetualFeeParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryPerpetualFeeParamsResponse) Reset()         { *m = QueryPerpetualFeeParamsResponse{} }
func (m *QueryPerpetualFeeParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPerpetualFeeParamsResponse) ProtoMessage()    {}
func (*QueryPerpetualFeeParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{1}
}
func (m *QueryPerpetualFeeParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPerpetualFeeParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPerpetualFeeParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPerpetualFeeParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPerpetualFeeParamsResponse.Merge(m, src)
}
func (m *QueryPerpetualFeeParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPerpetualFeeParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPerpetualFeeParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPerpetualFeeParamsResponse proto.InternalMessageInfo

func (m *QueryPerpetualFeeParamsResponse) GetParams() PerpetualFeeParams {
	if m != nil {
		return m.Params
	}
	return PerpetualFeeParams{}
}

// QuerySpotFeeParamsRequest is the request type for SpotFeeParams.
type QuerySpotFeeParamsRequest struct {
}

func (m *QuerySpotFeeParamsRequest) Reset()         { *m = QuerySpotFeeParamsRequest{} }
func (m *QuerySpotFeeParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySpotFeeParamsRequest) ProtoMessage()    {}
func (*QuerySpotFeeParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{2}
}
func (m *QuerySpotFeeParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySpotFeeParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySpotFeeParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySpotFeeParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySpotFeeParamsRequest.Merge(m, src)
}
func (m *QuerySpotFeeParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySpotFeeParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySpotFeeParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySpotFeeParamsRequest proto.InternalMessageInfo

// QuerySpotFeeParamsResponse is the response type for SpotFeeParams.
type QuerySpotFeeParamsResponse struct {
	Params SpotFeeParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QuerySpotFeeParamsResponse) Reset()         { *m = QuerySpotFeeParamsResponse{} }
func (m *QuerySpotFeeParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySpotFeeParamsResponse) ProtoMessage()    {}
func (*QuerySpotFeeParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{3}
}
func (m *QuerySpotFeeParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySpotFeeParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySpotFeeParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySpotFeeParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySpotFeeParamsResponse.Merge(m, src)
}
func (m *QuerySpotFeeParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySpotFeeParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySpotFeeParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySpotFeeParamsResponse proto.InternalMessageInfo

func (m *QuerySpotFeeParamsResponse) GetParams() SpotFeeParams {
	if m != nil {
		return m.Params
	}
	return SpotFeeParams{}
}

// QueryUserFeeTierRequest is a request type for the UserFeeTier RPC method.
type QueryUserFeeTierRequest struct {
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (m *QueryUserFeeTierRequest) Reset()         { *m = QueryUserFeeTierRequest{} }
func (m *QueryUserFeeTierRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserFeeTierRequest) ProtoMessage()    {}
func (*QueryUserFeeTierRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{4}
}
func (m *QueryUserFeeTierRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserFeeTierRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserFeeTierRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserFeeTierRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserFeeTierRequest.Merge(m, src)
}
func (m *QueryUserFeeTierRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserFeeTierRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserFeeTierRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserFeeTierRequest proto.InternalMessageInfo

func (m *QueryUserFeeTierRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

// QueryUserFeeTierResponse is a request type for the UserFeeTier RPC method.
type QueryUserFeeTierResponse struct {
	// Index of the fee tier in the list queried from PerpetualFeeParams.
	Index uint32            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Tier  *PerpetualFeeTier `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
}

func (m *QueryUserFeeTierResponse) Reset()         { *m = QueryUserFeeTierResponse{} }
func (m *QueryUserFeeTierResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserFeeTierResponse) ProtoMessage()    {}
func (*QueryUserFeeTierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{5}
}
func (m *QueryUserFeeTierResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserFeeTierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserFeeTierResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserFeeTierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserFeeTierResponse.Merge(m, src)
}
func (m *QueryUserFeeTierResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserFeeTierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserFeeTierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserFeeTierResponse proto.InternalMessageInfo

func (m *QueryUserFeeTierResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *QueryUserFeeTierResponse) GetTier() *PerpetualFeeTier {
	if m != nil {
		return m.Tier
	}
	return nil
}

// QueryPerMarketFeeDiscountParamsRequest is the request type for the
// Query/PerMarketFeeDiscountParams RPC method.
type QueryPerMarketFeeDiscountParamsRequest struct {
	ClobPairId uint32 `protobuf:"varint,1,opt,name=clob_pair_id,json=clobPairId,proto3" json:"clob_pair_id,omitempty"`
}

func (m *QueryPerMarketFeeDiscountParamsRequest) Reset() {
	*m = QueryPerMarketFeeDiscountParamsRequest{}
}
func (m *QueryPerMarketFeeDiscountParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPerMarketFeeDiscountParamsRequest) ProtoMessage()    {}
func (*QueryPerMarketFeeDiscountParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{6}
}
func (m *QueryPerMarketFeeDiscountParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPerMarketFeeDiscountParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPerMarketFeeDiscountParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPerMarketFeeDiscountParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPerMarketFeeDiscountParamsRequest.Merge(m, src)
}
func (m *QueryPerMarketFeeDiscountParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPerMarketFeeDiscountParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPerMarketFeeDiscountParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPerMarketFeeDiscountParamsRequest proto.InternalMessageInfo

func (m *QueryPerMarketFeeDiscountParamsRequest) GetClobPairId() uint32 {
	if m != nil {
		return m.ClobPairId
	}
	return 0
}

// QueryPerMarketFeeDiscountParamsResponse is the response type for the
// Query/PerMarketFeeDiscountParams RPC method.
type QueryPerMarketFeeDiscountParamsResponse struct {
	Params PerMarketFeeDiscountParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryPerMarketFeeDiscountParamsResponse) Reset() {
	*m = QueryPerMarketFeeDiscountParamsResponse{}
}
func (m *QueryPerMarketFeeDiscountParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPerMarketFeeDiscountParamsResponse) ProtoMessage()    {}
func (*QueryPerMarketFeeDiscountParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{7}
}
func (m *QueryPerMarketFeeDiscountParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPerMarketFeeDiscountParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPerMarketFeeDiscountParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPerMarketFeeDiscountParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPerMarketFeeDiscountParamsResponse.Merge(m, src)
}
func (m *QueryPerMarketFeeDiscountParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPerMarketFeeDiscountParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPerMarketFeeDiscountParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPerMarketFeeDiscountParamsResponse proto.InternalMessageInfo

func (m *QueryPerMarketFeeDiscountParamsResponse) GetParams() PerMarketFeeDiscountParams {
	if m != nil {
		return m.Params
	}
	return PerMarketFeeDiscountParams{}
}

// QueryAllMarketFeeDiscountParamsRequest is the request type for the
// Query/AllMarketFeeDiscountParams RPC method.
type QueryAllMarketFeeDiscountParamsRequest struct {
}

func (m *QueryAllMarketFeeDiscountParamsRequest) Reset() {
	*m = QueryAllMarketFeeDiscountParamsRequest{}
}
func (m *QueryAllMarketFeeDiscountParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMarketFeeDiscountParamsRequest) ProtoMessage()    {}
func (*QueryAllMarketFeeDiscountParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{8}
}
func (m *QueryAllMarketFeeDiscountParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMarketFeeDiscountParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMarketFeeDiscountParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMarketFeeDiscountParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMarketFeeDiscountParamsRequest.Merge(m, src)
}
func (m *QueryAllMarketFeeDiscountParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMarketFeeDiscountParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMarketFeeDiscountParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMarketFeeDiscountParamsRequest proto.InternalMessageInfo

// QueryAllMarketFeeDiscountParamsResponse is the response type for the
// Query/AllMarketFeeDiscountParams RPC method.
type QueryAllMarketFeeDiscountParamsResponse struct {
	Params []PerMarketFeeDiscountParams `protobuf:"bytes,1,rep,name=params,proto3" json:"params"`
}

func (m *QueryAllMarketFeeDiscountParamsResponse) Reset() {
	*m = QueryAllMarketFeeDiscountParamsResponse{}
}
func (m *QueryAllMarketFeeDiscountParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMarketFeeDiscountParamsResponse) ProtoMessage()    {}
func (*QueryAllMarketFeeDiscountParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{9}
}
func (m *QueryAllMarketFeeDiscountParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMarketFeeDiscountParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMarketFeeDiscountParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMarketFeeDiscountParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMarketFeeDiscountParamsResponse.Merge(m, src)
}
func (m *QueryAllMarketFeeDiscountParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMarketFeeDiscountParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMarketFeeDiscountParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMarketFeeDiscountParamsResponse proto.InternalMessageInfo

func (m *QueryAllMarketFeeDiscountParamsResponse) GetParams() []PerMarketFeeDiscountParams {
	if m != nil {
		return m.Params
	}
	return nil
}

// QueryStakingTiersRequest is a request type for the StakingTiers RPC method.
type QueryStakingTiersRequest struct {
}

func (m *QueryStakingTiersRequest) Reset()         { *m = QueryStakingTiersRequest{} }
func (m *QueryStakingTiersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStakingTiersRequest) ProtoMessage()    {}
func (*QueryStakingTiersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{10}
}
func (m *QueryStakingTiersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakingTiersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakingTiersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakingTiersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakingTiersRequest.Merge(m, src)
}
func (m *QueryStakingTiersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakingTiersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakingTiersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakingTiersRequest proto.InternalMessageInfo

// QueryStakingTiersResponse is a response type for the StakingTiers RPC method.
type QueryStakingTiersResponse struct {
	StakingTiers []*StakingTier `protobuf:"bytes,1,rep,name=staking_tiers,json=stakingTiers,proto3" json:"staking_tiers,omitempty"`
}

func (m *QueryStakingTiersResponse) Reset()         { *m = QueryStakingTiersResponse{} }
func (m *QueryStakingTiersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStakingTiersResponse) ProtoMessage()    {}
func (*QueryStakingTiersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{11}
}
func (m *QueryStakingTiersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakingTiersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakingTiersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakingTiersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakingTiersResponse.Merge(m, src)
}
func (m *QueryStakingTiersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakingTiersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakingTiersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakingTiersResponse proto.InternalMessageInfo

func (m *QueryStakingTiersResponse) GetStakingTiers() []*StakingTier {
	if m != nil {
		return m.StakingTiers
	}
	return nil
}

// QueryUserStakingTierRequest is a request type for the UserStakingTier RPC
// method.
type QueryUserStakingTierRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryUserStakingTierRequest) Reset()         { *m = QueryUserStakingTierRequest{} }
func (m *QueryUserStakingTierRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserStakingTierRequest) ProtoMessage()    {}
func (*QueryUserStakingTierRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{12}
}
func (m *QueryUserStakingTierRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserStakingTierRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserStakingTierRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserStakingTierRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserStakingTierRequest.Merge(m, src)
}
func (m *QueryUserStakingTierRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserStakingTierRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserStakingTierRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserStakingTierRequest proto.InternalMessageInfo

func (m *QueryUserStakingTierRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryUserStakingTierResponse is a response type for the UserStakingTier RPC
// method.
type QueryUserStakingTierResponse struct {
	// The user's current fee tier name
	FeeTierName string `protobuf:"bytes,1,opt,name=fee_tier_name,json=feeTierName,proto3" json:"fee_tier_name,omitempty"`
	// Amount of tokens staked by the user (in base units)
	StakedBaseTokens github_com_dydxprotocol_v4_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,2,opt,name=staked_base_tokens,json=stakedBaseTokens,proto3,customtype=github.com/dydxprotocol/v4-chain/protocol/dtypes.SerializableInt" json:"staked_base_tokens"`
	// The discount percentage in ppm that user qualifies for
	DiscountPpm uint32 `protobuf:"varint,3,opt,name=discount_ppm,json=discountPpm,proto3" json:"discount_ppm,omitempty"`
}

func (m *QueryUserStakingTierResponse) Reset()         { *m = QueryUserStakingTierResponse{} }
func (m *QueryUserStakingTierResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserStakingTierResponse) ProtoMessage()    {}
func (*QueryUserStakingTierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f31456045d64644f, []int{13}
}
func (m *QueryUserStakingTierResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserStakingTierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserStakingTierResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserStakingTierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserStakingTierResponse.Merge(m, src)
}
func (m *QueryUserStakingTierResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserStakingTierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserStakingTierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserStakingTierResponse proto.InternalMessageInfo

func (m *QueryUserStakingTierResponse) GetFeeTierName() string {
	if m != nil {
		return m.FeeTierName
	}
	return ""
}

func (m *QueryUserStakingTierResponse) GetDiscountPpm() uint32 {
	if m != nil {
		return m.DiscountPpm
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryPerpetualFeeParamsRequest)(nil), "dydxprotocol.feetiers.QueryPerpetualFeeParamsRequest")
	proto.RegisterType((*QueryPerpetualFeeParamsResponse)(nil), "dydxprotocol.feetiers.QueryPerpetualFeeParamsResponse")
	proto.RegisterType((*QuerySpotFeeParamsRequest)(nil), "dydxprotocol.feetiers.QuerySpotFeeParamsRequest")
	proto.RegisterType((*QuerySpotFeeParamsResponse)(nil), "dydxprotocol.feetiers.QuerySpotFeeParamsResponse")
	proto.RegisterType((*QueryUserFeeTierRequest)(nil), "dydxprotocol.feetiers.QueryUserFeeTierRequest")
	proto.RegisterType((*QueryUserFeeTierResponse)(nil), "dydxprotocol.feetiers.QueryUserFeeTierResponse")
	proto.RegisterType((*QueryPerMarketFeeDiscountParamsRequest)(nil), "dydxprotocol.feetiers.QueryPerMarketFeeDiscountParamsRequest")
	proto.RegisterType((*QueryPerMarketFeeDiscountParamsResponse)(nil), "dydxprotocol.feetiers.QueryPerMarketFeeDiscountParamsResponse")
	proto.RegisterType((*QueryAllMarketFeeDiscountParamsRequest)(nil), "dydxprotocol.feetiers.QueryAllMarketFeeDiscountParamsRequest")
	proto.RegisterType((*QueryAllMarketFeeDiscountParamsResponse)(nil), "dydxprotocol.feetiers.QueryAllMarketFeeDiscountParamsResponse")
	proto.RegisterType((*QueryStakingTiersRequest)(nil), "dydxprotocol.feetiers.QueryStakingTiersRequest")
	proto.RegisterType((*QueryStakingTiersResponse)(nil), "dydxprotocol.feetiers.QueryStakingTiersResponse")
	proto.RegisterType((*QueryUserStakingTierRequest)(nil), "dydxprotocol.feetiers.QueryUserStakingTierRequest")
	proto.RegisterType((*QueryUserStakingTierResponse)(nil), "dydxprotocol.feetiers.QueryUserStakingTierResponse")
}

func init() { proto.RegisterFile("dydxprotocol/feetiers/query.proto", fileDescriptor_f31456045d64644f) }

var fileDescriptor_f31456045d64644f = []byte{
	// 904 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xc7, 0xe3, 0xdd, 0xee, 0x22, 0x26, 0x89, 0x40, 0xa3, 0x22, 0xb2, 0xde, 0x55, 0xda, 0xb5,
	0x10, 0x6d, 0x05, 0x6b, 0xb7, 0xe9, 0x6e, 0x91, 0x80, 0x45, 0x34, 0x40, 0x4b, 0x41, 0x40, 0x9a,
	0x94, 0x0b, 0x17, 0x33, 0x89, 0x9f, 0xa6, 0xa6, 0xb6, 0xc7, 0xf5, 0x4c, 0xaa, 0xbe, 0xa8, 0x17,
	0x3e, 0x01, 0x12, 0x1f, 0x00, 0x89, 0x0b, 0x5f, 0x80, 0x4b, 0xc5, 0x17, 0xe8, 0xb1, 0x82, 0x0b,
	0x20, 0x51, 0xa1, 0x96, 0x03, 0x1f, 0x03, 0x79, 0x3c, 0x4e, 0x9d, 0xc4, 0x76, 0xd2, 0x8a, 0x5b,
	0x3d, 0xf3, 0xbc, 0xfc, 0x9e, 0x97, 0xf9, 0x37, 0xe8, 0xb1, 0x75, 0x68, 0x1d, 0xf8, 0x01, 0xe5,
	0xb4, 0x43, 0x1d, 0x63, 0x1b, 0x80, 0xdb, 0x10, 0x30, 0x63, 0xaf, 0x07, 0xc1, 0xa1, 0x2e, 0xce,
	0xf1, 0x2b, 0x49, 0x13, 0x3d, 0x36, 0x51, 0x1f, 0x74, 0x28, 0x73, 0x29, 0x33, 0xc5, 0x8d, 0x11,
	0x7d, 0x44, 0x1e, 0xea, 0x74, 0x97, 0x76, 0x69, 0x74, 0x1e, 0xfe, 0x25, 0x4f, 0x1f, 0x75, 0x29,
	0xed, 0x3a, 0x60, 0x10, 0xdf, 0x36, 0x88, 0xe7, 0x51, 0x4e, 0xb8, 0x4d, 0xbd, 0xd8, 0x47, 0x4b,
	0x07, 0xf1, 0x49, 0x40, 0xdc, 0xd8, 0x66, 0x39, 0xc3, 0x06, 0x02, 0xd3, 0x25, 0xc1, 0x2e, 0x70,
	0x73, 0x1b, 0xc0, 0xb4, 0x6c, 0xd6, 0xa1, 0x3d, 0x8f, 0x4b, 0xa7, 0xf9, 0x74, 0x27, 0xc6, 0xc9,
	0xae, 0xed, 0x75, 0xcd, 0xf0, 0x2b, 0xb2, 0xd4, 0x66, 0x51, 0x75, 0x33, 0xac, 0xbb, 0x01, 0x81,
	0x0f, 0xbc, 0x47, 0x9c, 0x35, 0x80, 0x86, 0xc8, 0xdf, 0x84, 0xbd, 0x1e, 0x30, 0xae, 0x7d, 0x83,
	0x66, 0x32, 0x2d, 0x98, 0x4f, 0x3d, 0x06, 0x78, 0x1d, 0xdd, 0x8f, 0x98, 0x2b, 0xca, 0xac, 0x32,
	0x5f, 0xac, 0x2d, 0xe8, 0xa9, 0xed, 0xd3, 0x47, 0x43, 0xd4, 0xa7, 0xce, 0x2e, 0x66, 0x0a, 0x4d,
	0xe9, 0xae, 0x3d, 0x44, 0x0f, 0x44, 0xae, 0x96, 0x4f, 0xf9, 0x08, 0xc8, 0xd7, 0x48, 0x4d, 0xbb,
	0x94, 0x0c, 0xf5, 0x21, 0x86, 0xd7, 0x32, 0x18, 0x06, 0xbc, 0x87, 0xd2, 0xaf, 0xa3, 0x57, 0x45,
	0x86, 0x2f, 0x19, 0x04, 0x6b, 0x00, 0x5b, 0x36, 0x04, 0x32, 0x39, 0x7e, 0x13, 0x4d, 0xf5, 0x18,
	0x04, 0x22, 0xf8, 0x8b, 0xf5, 0xca, 0xaf, 0x3f, 0x3f, 0x99, 0x96, 0xe3, 0x5f, 0xb5, 0xac, 0x00,
	0x18, 0x6b, 0xf1, 0xc0, 0xf6, 0xba, 0x4d, 0x61, 0xa5, 0xb9, 0xa8, 0x32, 0x1a, 0x48, 0x82, 0x4e,
	0xa3, 0x7b, 0xb6, 0x67, 0xc1, 0x81, 0x08, 0x55, 0x6e, 0x46, 0x1f, 0xf8, 0x1d, 0x34, 0x15, 0xf2,
	0x55, 0xee, 0x08, 0xf8, 0xb9, 0x09, 0x1a, 0x28, 0x82, 0x0a, 0x27, 0xed, 0x13, 0xf4, 0x7a, 0x3c,
	0xa2, 0xcf, 0xc4, 0x4e, 0xac, 0x01, 0x7c, 0x28, 0x37, 0x62, 0xa0, 0x87, 0x78, 0x16, 0x95, 0x3a,
	0x0e, 0x6d, 0x9b, 0x3e, 0xb1, 0x03, 0xd3, 0xb6, 0x24, 0x03, 0x0a, 0xcf, 0x1a, 0xc4, 0x0e, 0x36,
	0x2c, 0xed, 0x08, 0xcd, 0x8d, 0x8d, 0x25, 0x2b, 0xf9, 0x62, 0xa8, 0xe5, 0x4b, 0xd9, 0xd4, 0x19,
	0xa1, 0x86, 0xfa, 0x3f, 0x2f, 0xeb, 0x58, 0x75, 0x9c, 0xfc, 0x3a, 0xfa, 0x94, 0x79, 0x96, 0x29,
	0x94, 0x77, 0xff, 0x0f, 0x4a, 0x55, 0x0e, 0xb7, 0x15, 0xbd, 0xa6, 0x70, 0x0e, 0x7d, 0x2e, 0x2b,
	0x5e, 0xe0, 0x81, 0xbb, 0xfe, 0x33, 0x29, 0x27, 0x5f, 0x60, 0x0c, 0xa4, 0x65, 0x6d, 0xea, 0x75,
	0x8c, 0x66, 0x89, 0x25, 0x02, 0x6a, 0x9b, 0xe8, 0x61, 0x7f, 0xbd, 0x92, 0x56, 0x72, 0xc8, 0x35,
	0xf4, 0x02, 0x89, 0x96, 0x72, 0xec, 0xba, 0xc6, 0x86, 0xda, 0x5f, 0x0a, 0x7a, 0x94, 0x1e, 0x53,
	0xc2, 0x6b, 0xa8, 0x1c, 0x0a, 0x4d, 0x88, 0x66, 0x7a, 0xc4, 0x85, 0x28, 0x74, 0xb3, 0xb8, 0x1d,
	0x6d, 0xe2, 0xe7, 0xc4, 0x05, 0xbc, 0x8f, 0x70, 0xc8, 0x09, 0x96, 0xd9, 0x26, 0x0c, 0x4c, 0x4e,
	0x77, 0xc1, 0x63, 0x62, 0xa5, 0x4b, 0xf5, 0x8f, 0xc3, 0x1e, 0xfe, 0x79, 0x31, 0xf3, 0x7e, 0xd7,
	0xe6, 0x3b, 0xbd, 0xb6, 0xde, 0xa1, 0xae, 0x31, 0xa0, 0x52, 0xfb, 0x4f, 0x9f, 0x74, 0x76, 0x88,
	0xed, 0x19, 0xfd, 0x13, 0x8b, 0x1f, 0xfa, 0xc0, 0xf4, 0x16, 0x04, 0x36, 0x71, 0xec, 0x23, 0xd2,
	0x76, 0x60, 0xc3, 0xe3, 0xcd, 0x97, 0xa3, 0x1c, 0x75, 0xc2, 0x60, 0x4b, 0x64, 0xc0, 0x8f, 0x51,
	0x29, 0x16, 0x40, 0xd3, 0xf7, 0xdd, 0xca, 0x5d, 0xb1, 0xd5, 0xc5, 0xf8, 0xac, 0xe1, 0xbb, 0xb5,
	0x53, 0x84, 0xee, 0x89, 0xfa, 0xf0, 0x2f, 0x0a, 0xc2, 0xa3, 0x42, 0x84, 0x9f, 0x65, 0x4c, 0x21,
	0x5f, 0x1d, 0xd5, 0x95, 0x9b, 0xba, 0x45, 0xed, 0xd4, 0x56, 0xbe, 0xfd, 0xed, 0x9f, 0xef, 0xef,
	0x2c, 0x62, 0x7d, 0xb8, 0x09, 0x03, 0x12, 0x1f, 0x79, 0x0b, 0x85, 0x8f, 0x96, 0x0f, 0xff, 0xa4,
	0xa0, 0xf2, 0x80, 0x84, 0xe1, 0xc5, 0x3c, 0x82, 0x34, 0x21, 0x55, 0x97, 0x6e, 0xe0, 0x21, 0x71,
	0x97, 0x04, 0xee, 0x1b, 0x78, 0x21, 0x1b, 0x97, 0xf9, 0x94, 0x27, 0x49, 0x7f, 0x50, 0x50, 0x31,
	0xa1, 0x7f, 0x58, 0xcf, 0xcb, 0x3a, 0xaa, 0xb8, 0xaa, 0x31, 0xb1, 0xbd, 0x64, 0x34, 0x04, 0xe3,
	0x02, 0x9e, 0xcb, 0x66, 0x0c, 0xc5, 0xd9, 0x8c, 0xd7, 0x18, 0xff, 0xab, 0x20, 0x35, 0xfb, 0xd5,
	0xe3, 0xe7, 0x63, 0x46, 0x9b, 0x2f, 0x51, 0xea, 0x7b, 0xb7, 0x75, 0x97, 0xe5, 0x7c, 0x2a, 0xca,
	0xf9, 0x08, 0x7f, 0x90, 0x5d, 0x4e, 0xca, 0x0f, 0x00, 0xd9, 0x7d, 0xe3, 0x38, 0x29, 0xf3, 0x27,
	0xf8, 0x0f, 0x05, 0xa9, 0xd9, 0x5a, 0x99, 0x5f, 0xea, 0x58, 0x35, 0xce, 0x2f, 0x75, 0xbc, 0x44,
	0x6b, 0xef, 0x8a, 0x52, 0x57, 0xf0, 0xd3, 0xdb, 0x94, 0x8a, 0x7f, 0x54, 0x50, 0x29, 0xa9, 0xb7,
	0x38, 0x77, 0x73, 0x52, 0x54, 0x5b, 0x5d, 0x9c, 0xdc, 0x61, 0xf2, 0x5d, 0x1b, 0x90, 0x7a, 0x7c,
	0xaa, 0xa0, 0x97, 0x86, 0xa4, 0x15, 0xd7, 0xc6, 0x6d, 0xf8, 0xa8, 0xb6, 0xab, 0xcb, 0x37, 0xf2,
	0x91, 0xb4, 0xcf, 0x05, 0xed, 0x5b, 0xf8, 0xd9, 0x98, 0x97, 0x91, 0x44, 0x36, 0x8e, 0xe5, 0xbf,
	0x86, 0x93, 0xfa, 0xd6, 0xd9, 0x65, 0x55, 0x39, 0xbf, 0xac, 0x2a, 0x7f, 0x5f, 0x56, 0x95, 0xef,
	0xae, 0xaa, 0x85, 0xf3, 0xab, 0x6a, 0xe1, 0xf7, 0xab, 0x6a, 0xe1, 0xab, 0xb7, 0x27, 0x17, 0xf3,
	0x83, 0xeb, 0x5c, 0x42, 0xd6, 0xdb, 0xf7, 0xc5, 0xd5, 0xf2, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa7, 0x85, 0x4e, 0x32, 0x8e, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries the PerpetualFeeParams.
	PerpetualFeeParams(ctx context.Context, in *QueryPerpetualFeeParamsRequest, opts ...grpc.CallOption) (*QueryPerpetualFeeParamsResponse, error)
	// Queries the SpotFeeParams.
	SpotFeeParams(ctx context.Context, in *QuerySpotFeeParamsRequest, opts ...grpc.CallOption) (*QuerySpotFeeParamsResponse, error)
	// Queries a user's fee tier
	UserFeeTier(ctx context.Context, in *QueryUserFeeTierRequest, opts ...grpc.CallOption) (*QueryUserFeeTierResponse, error)
	// PerMarketFeeDiscountParams queries fee discount parameters for a
	// specific market/CLOB pair.
	PerMarketFeeDiscountParams(ctx context.Context, in *QueryPerMarketFeeDiscountParamsRequest, opts ...grpc.CallOption) (*QueryPerMarketFeeDiscountParamsResponse, error)
	// AllMarketFeeDiscountParams queries all per-market fee discount parameters.
	AllMarketFeeDiscountParams(ctx context.Context, in *QueryAllMarketFeeDiscountParamsRequest, opts ...grpc.CallOption) (*QueryAllMarketFeeDiscountParamsResponse, error)
	// Get all staking tiers
	StakingTiers(ctx context.Context, in *QueryStakingTiersRequest, opts ...grpc.CallOption) (*QueryStakingTiersResponse, error)
	// Get user's current staked amount and staking tier
	UserStakingTier(ctx context.Context, in *QueryUserStakingTierRequest, opts ...grpc.CallOption) (*QueryUserStakingTierResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PerpetualFeeParams(ctx context.Context, in *QueryPerpetualFeeParamsRequest, opts ...grpc.CallOption) (*QueryPerpetualFeeParamsResponse, error) {
	out := new(QueryPerpetualFeeParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Query/PerpetualFeeParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotFeeParams(ctx context.Context, in *QuerySpotFeeParamsRequest, opts ...grpc.CallOption) (*QuerySpotFeeParamsResponse, error) {
	out := new(QuerySpotFeeParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Query/SpotFeeParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserFeeTier(ctx context.Context, in *QueryUserFeeTierRequest, opts ...grpc.CallOption) (*QueryUserFeeTierResponse, error) {
	out := new(QueryUserFeeTierResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Query/UserFeeTier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PerMarketFeeDiscountParams(ctx context.Context, in *QueryPerMarketFeeDiscountParamsRequest, opts ...grpc.CallOption) (*QueryPerMarketFeeDiscountParamsResponse, error) {
	out := new(QueryPerMarketFeeDiscountParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Query/PerMarketFeeDiscountParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllMarketFeeDiscountParams(ctx context.Context, in *QueryAllMarketFeeDiscountParamsRequest, opts ...grpc.CallOption) (*QueryAllMarketFeeDiscountParamsResponse, error) {
	out := new(QueryAllMarketFeeDiscountParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Query/AllMarketFeeDiscountParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StakingTiers(ctx context.Context, in *QueryStakingTiersRequest, opts ...grpc.CallOption) (*QueryStakingTiersResponse, error) {
	out := new(QueryStakingTiersResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Query/StakingTiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserStakingTier(ctx context.Context, in *QueryUserStakingTierRequest, opts ...grpc.CallOption) (*QueryUserStakingTierResponse, error) {
	out := new(QueryUserStakingTierResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Query/UserStakingTier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries the PerpetualFeeParams.
	PerpetualFeeParams(context.Context, *QueryPerpetualFeeParamsRequest) (*QueryPerpetualFeeParamsResponse, error)
	// Queries the SpotFeeParams.
	SpotFeeParams(context.Context, *QuerySpotFeeParamsRequest) (*QuerySpotFeeParamsResponse, error)
	// Queries a user's fee tier
	UserFeeTier(context.Context, *QueryUserFeeTierRequest) (*QueryUserFeeTierResponse, error)
	// PerMarketFeeDiscountParams queries fee discount parameters for a
	// specific market/CLOB pair.
	PerMarketFeeDiscountParams(context.Context, *QueryPerMarketFeeDiscountParamsRequest) (*QueryPerMarketFeeDiscountParamsResponse, error)
	// AllMarketFeeDiscountParams queries all per-market fee discount parameters.
	AllMarketFeeDiscountParams(context.Context, *QueryAllMarketFeeDiscountParamsRequest) (*QueryAllMarketFeeDiscountParamsResponse, error)
	// Get all staking tiers
	StakingTiers(context.Context, *QueryStakingTiersRequest) (*QueryStakingTiersResponse, error)
	// Get user's current staked amount and staking tier
	UserStakingTier(context.Context, *QueryUserStakingTierRequest) (*QueryUserStakingTierResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PerpetualFeeParams(ctx context.Context, req *QueryPerpetualFeeParamsRequest) (*QueryPerpetualFeeParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerpetualFeeParams not implemented")
}
func (*UnimplementedQueryServer) SpotFeeParams(ctx context.Context, req *QuerySpotFeeParamsRequest) (*QuerySpotFeeParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotFeeParams not implemented")
}
func (*UnimplementedQueryServer) UserFeeTier(ctx context.Context, req *QueryUserFeeTierRequest) (*QueryUserFeeTierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserFeeTier not implemented")
}
func (*UnimplementedQueryServer) PerMarketFeeDiscountParams(ctx context.Context, req *QueryPerMarketFeeDiscountParamsRequest) (*QueryPerMarketFeeDiscountParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerMarketFeeDiscountParams not implemented")
}
func (*UnimplementedQueryServer) AllMarketFeeDiscountParams(ctx context.Context, req *QueryAllMarketFeeDiscountParamsRequest) (*QueryAllMarketFeeDiscountParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllMarketFeeDiscountParams not implemented")
}
func (*UnimplementedQueryServer) StakingTiers(ctx context.Context, req *QueryStakingTiersRequest) (*QueryStakingTiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakingTiers not implemented")
}
func (*UnimplementedQueryServer) UserStakingTier(ctx context.Context, req *QueryUserStakingTierRequest) (*QueryUserStakingTierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserStakingTier not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PerpetualFeeParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPerpetualFeeParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PerpetualFeeParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Query/PerpetualFeeParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PerpetualFeeParams(ctx, req.(*QueryPerpetualFeeParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotFeeParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotFeeParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotFeeParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Query/SpotFeeParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotFeeParams(ctx, req.(*QuerySpotFeeParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserFeeTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserFeeTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserFeeTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Query/UserFeeTier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserFeeTier(ctx, req.(*QueryUserFeeTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PerMarketFeeDiscountParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPerMarketFeeDiscountParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PerMarketFeeDiscountParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Query/PerMarketFeeDiscountParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PerMarketFeeDiscountParams(ctx, req.(*QueryPerMarketFeeDiscountParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllMarketFeeDiscountParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMarketFeeDiscountParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllMarketFeeDiscountParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Query/AllMarketFeeDiscountParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllMarketFeeDiscountParams(ctx, req.(*QueryAllMarketFeeDiscountParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StakingTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStakingTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StakingTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Query/StakingTiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StakingTiers(ctx, req.(*QueryStakingTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserStakingTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserStakingTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserStakingTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Query/UserStakingTier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserStakingTier(ctx, req.(*QueryUserStakingTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dydxprotocol.feetiers.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PerpetualFeeParams",
			Handler:    _Query_PerpetualFeeParams_Handler,
		},
		{
			MethodName: "SpotFeeParams",
			Handler:    _Query_SpotFeeParams_Handler,
		},
		{
			MethodName: "UserFeeTier",
			Handler:    _Query_UserFeeTier_Handler,
		},
		{
			MethodName: "PerMarketFeeDiscountParams",
			Handler:    _Query_PerMarketFeeDiscountParams_Handler,
		},
		{
			MethodName: "AllMarketFeeDiscountParams",
			Handler:    _Query_AllMarketFeeDiscountParams_Handler,
		},
		{
			MethodName: "StakingTiers",
			Handler:    _Query_StakingTiers_Handler,
		},
		{
			MethodName: "UserStakingTier",
			Handler:    _Query_UserStakingTier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dydxprotocol/feetiers/query.proto",
}

func (m *QueryPerpetualFeeParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPerpetualFeeParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPerpetualFeeParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPerpetualFeeParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPerpetualFeeParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPerpetualFeeParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QuerySpotFeeParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySpotFeeParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySpotFeeParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySpotFeeParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySpotFeeParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySpotFeeParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryUserFeeTierRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserFeeTierRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserFeeTierRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserFeeTierResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserFeeTierResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserFeeTierResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Tier != nil {
		{
			size, err := m.Tier.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPerMarketFeeDiscountParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPerMarketFeeDiscountParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPerMarketFeeDiscountParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClobPairId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ClobPairId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPerMarketFeeDiscountParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPerMarketFeeDiscountParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPerMarketFeeDiscountParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMarketFeeDiscountParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMarketFeeDiscountParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMarketFeeDiscountParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllMarketFeeDiscountParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMarketFeeDiscountParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMarketFeeDiscountParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Params) > 0 {
		for iNdEx := len(m.Params) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Params[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakingTiersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakingTiersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakingTiersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryStakingTiersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakingTiersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakingTiersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StakingTiers) > 0 {
		for iNdEx := len(m.StakingTiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingTiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserStakingTierRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserStakingTierRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserStakingTierRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserStakingTierResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserStakingTierResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserStakingTierResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DiscountPpm != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DiscountPpm))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.StakedBaseTokens.Size()
		i -= size
		if _, err := m.StakedBaseTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.FeeTierName) > 0 {
		i -= len(m.FeeTierName)
		copy(dAtA[i:], m.FeeTierName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeeTierName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPerpetualFeeParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPerpetualFeeParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QuerySpotFeeParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySpotFeeParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryUserFeeTierRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserFeeTierResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovQuery(uint64(m.Index))
	}
	if m.Tier != nil {
		l = m.Tier.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPerMarketFeeDiscountParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClobPairId != 0 {
		n += 1 + sovQuery(uint64(m.ClobPairId))
	}
	return n
}

func (m *QueryPerMarketFeeDiscountParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMarketFeeDiscountParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllMarketFeeDiscountParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Params) > 0 {
		for _, e := range m.Params {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryStakingTiersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryStakingTiersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StakingTiers) > 0 {
		for _, e := range m.StakingTiers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryUserStakingTierRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserStakingTierResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeeTierName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.StakedBaseTokens.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.DiscountPpm != 0 {
		n += 1 + sovQuery(uint64(m.DiscountPpm))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPerpetualFeeParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPerpetualFeeParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPerpetualFeeParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPerpetualFeeParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPerpetualFeeParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPerpetualFeeParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySpotFeeParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySpotFeeParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySpotFeeParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySpotFeeParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySpotFeeParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySpotFeeParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserFeeTierRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserFeeTierRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserFeeTierRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserFeeTierResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserFeeTierResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserFeeTierResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tier == nil {
				m.Tier = &PerpetualFeeTier{}
			}
			if err := m.Tier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPerMarketFeeDiscountParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPerMarketFeeDiscountParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPerMarketFeeDiscountParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClobPairId", wireType)
			}
			m.ClobPairId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClobPairId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPerMarketFeeDiscountParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPerMarketFeeDiscountParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPerMarketFeeDiscountParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMarketFeeDiscountParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMarketFeeDiscountParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMarketFeeDiscountParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMarketFeeDiscountParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMarketFeeDiscountParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMarketFeeDiscountParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = append(m.Params, PerMarketFeeDiscountParams{})
			if err := m.Params[len(m.Params)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakingTiersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakingTiersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakingTiersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakingTiersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakingTiersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakingTiersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingTiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingTiers = append(m.StakingTiers, &StakingTier{})
			if err := m.StakingTiers[len(m.StakingTiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserStakingTierRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserStakingTierRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserStakingTierRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserStakingTierResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserStakingTierResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserStakingTierResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeTierName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeTierName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedBaseTokens", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakedBaseTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountPpm", wireType)
			}
			m.DiscountPpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiscountPpm |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
