// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/feetiers/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdatePerpetualFeeParams is the Msg/UpdatePerpetualFeeParams request type.
type MsgUpdatePerpetualFeeParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Defines the parameters to update. All parameters must be supplied.
	Params PerpetualFeeParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdatePerpetualFeeParams) Reset()         { *m = MsgUpdatePerpetualFeeParams{} }
func (m *MsgUpdatePerpetualFeeParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePerpetualFeeParams) ProtoMessage()    {}
func (*MsgUpdatePerpetualFeeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{0}
}
func (m *MsgUpdatePerpetualFeeParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePerpetualFeeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePerpetualFeeParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePerpetualFeeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePerpetualFeeParams.Merge(m, src)
}
func (m *MsgUpdatePerpetualFeeParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePerpetualFeeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePerpetualFeeParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePerpetualFeeParams proto.InternalMessageInfo

func (m *MsgUpdatePerpetualFeeParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdatePerpetualFeeParams) GetParams() PerpetualFeeParams {
	if m != nil {
		return m.Params
	}
	return PerpetualFeeParams{}
}

// MsgUpdatePerpetualFeeParamsResponse is the Msg/UpdatePerpetualFeeParams
// response type.
type MsgUpdatePerpetualFeeParamsResponse struct {
}

func (m *MsgUpdatePerpetualFeeParamsResponse) Reset()         { *m = MsgUpdatePerpetualFeeParamsResponse{} }
func (m *MsgUpdatePerpetualFeeParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePerpetualFeeParamsResponse) ProtoMessage()    {}
func (*MsgUpdatePerpetualFeeParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{1}
}
func (m *MsgUpdatePerpetualFeeParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePerpetualFeeParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePerpetualFeeParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePerpetualFeeParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePerpetualFeeParamsResponse.Merge(m, src)
}
func (m *MsgUpdatePerpetualFeeParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePerpetualFeeParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePerpetualFeeParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePerpetualFeeParamsResponse proto.InternalMessageInfo

// MsgUpdateSpotFeeParams is the Msg/UpdateSpotFeeParams request type.
type MsgUpdateSpotFeeParams struct {
	Authority     string        `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	SpotFeeParams SpotFeeParams `protobuf:"bytes,2,opt,name=spot_fee_params,json=spotFeeParams,proto3" json:"spot_fee_params"`
}

func (m *MsgUpdateSpotFeeParams) Reset()         { *m = MsgUpdateSpotFeeParams{} }
func (m *MsgUpdateSpotFeeParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSpotFeeParams) ProtoMessage()    {}
func (*MsgUpdateSpotFeeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{2}
}
func (m *MsgUpdateSpotFeeParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSpotFeeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSpotFeeParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSpotFeeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSpotFeeParams.Merge(m, src)
}
func (m *MsgUpdateSpotFeeParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSpotFeeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSpotFeeParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSpotFeeParams proto.InternalMessageInfo

func (m *MsgUpdateSpotFeeParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateSpotFeeParams) GetSpotFeeParams() SpotFeeParams {
	if m != nil {
		return m.SpotFeeParams
	}
	return SpotFeeParams{}
}

// MsgUpdateSpotFeeParamsResponse is the response type for updating spot fee parameters.
type MsgUpdateSpotFeeParamsResponse struct {
}

func (m *MsgUpdateSpotFeeParamsResponse) Reset()         { *m = MsgUpdateSpotFeeParamsResponse{} }
func (m *MsgUpdateSpotFeeParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSpotFeeParamsResponse) ProtoMessage()    {}
func (*MsgUpdateSpotFeeParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{3}
}
func (m *MsgUpdateSpotFeeParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSpotFeeParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSpotFeeParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSpotFeeParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSpotFeeParamsResponse.Merge(m, src)
}
func (m *MsgUpdateSpotFeeParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSpotFeeParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSpotFeeParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSpotFeeParamsResponse proto.InternalMessageInfo

// MsgSetMarketFeeDiscountParams is the Msg/SetMarketFeeDiscountParams
// request type.
type MsgSetMarketFeeDiscountParams struct {
	// authority is the address that controls the module
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// The per-market fee discount parameters to create or update
	Params []PerMarketFeeDiscountParams `protobuf:"bytes,2,rep,name=params,proto3" json:"params"`
}

func (m *MsgSetMarketFeeDiscountParams) Reset()         { *m = MsgSetMarketFeeDiscountParams{} }
func (m *MsgSetMarketFeeDiscountParams) String() string { return proto.CompactTextString(m) }
func (*MsgSetMarketFeeDiscountParams) ProtoMessage()    {}
func (*MsgSetMarketFeeDiscountParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{4}
}
func (m *MsgSetMarketFeeDiscountParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetMarketFeeDiscountParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetMarketFeeDiscountParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetMarketFeeDiscountParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetMarketFeeDiscountParams.Merge(m, src)
}
func (m *MsgSetMarketFeeDiscountParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetMarketFeeDiscountParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetMarketFeeDiscountParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetMarketFeeDiscountParams proto.InternalMessageInfo

func (m *MsgSetMarketFeeDiscountParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetMarketFeeDiscountParams) GetParams() []PerMarketFeeDiscountParams {
	if m != nil {
		return m.Params
	}
	return nil
}

// MsgSetMarketFeeDiscountParamsResponse is the
// Msg/SetMarketFeeDiscountParams response type.
type MsgSetMarketFeeDiscountParamsResponse struct {
}

func (m *MsgSetMarketFeeDiscountParamsResponse) Reset()         { *m = MsgSetMarketFeeDiscountParamsResponse{} }
func (m *MsgSetMarketFeeDiscountParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetMarketFeeDiscountParamsResponse) ProtoMessage()    {}
func (*MsgSetMarketFeeDiscountParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{5}
}
func (m *MsgSetMarketFeeDiscountParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetMarketFeeDiscountParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetMarketFeeDiscountParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetMarketFeeDiscountParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetMarketFeeDiscountParamsResponse.Merge(m, src)
}
func (m *MsgSetMarketFeeDiscountParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetMarketFeeDiscountParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetMarketFeeDiscountParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetMarketFeeDiscountParamsResponse proto.InternalMessageInfo

// MsgSetStakingTiers is the Msg/SetStakingTiers request type.
type MsgSetStakingTiers struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// List of Staking tiers
	StakingTiers []*StakingTier `protobuf:"bytes,2,rep,name=staking_tiers,json=stakingTiers,proto3" json:"staking_tiers,omitempty"`
}

func (m *MsgSetStakingTiers) Reset()         { *m = MsgSetStakingTiers{} }
func (m *MsgSetStakingTiers) String() string { return proto.CompactTextString(m) }
func (*MsgSetStakingTiers) ProtoMessage()    {}
func (*MsgSetStakingTiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{6}
}
func (m *MsgSetStakingTiers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetStakingTiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetStakingTiers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetStakingTiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetStakingTiers.Merge(m, src)
}
func (m *MsgSetStakingTiers) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetStakingTiers) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetStakingTiers.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetStakingTiers proto.InternalMessageInfo

func (m *MsgSetStakingTiers) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetStakingTiers) GetStakingTiers() []*StakingTier {
	if m != nil {
		return m.StakingTiers
	}
	return nil
}

// MsgSetStakingTiersResponse is the Msg/SetStakingTiers response type.
type MsgSetStakingTiersResponse struct {
}

func (m *MsgSetStakingTiersResponse) Reset()         { *m = MsgSetStakingTiersResponse{} }
func (m *MsgSetStakingTiersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetStakingTiersResponse) ProtoMessage()    {}
func (*MsgSetStakingTiersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa74a3b986b7fd9, []int{7}
}
func (m *MsgSetStakingTiersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetStakingTiersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetStakingTiersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetStakingTiersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetStakingTiersResponse.Merge(m, src)
}
func (m *MsgSetStakingTiersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetStakingTiersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetStakingTiersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetStakingTiersResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdatePerpetualFeeParams)(nil), "dydxprotocol.feetiers.MsgUpdatePerpetualFeeParams")
	proto.RegisterType((*MsgUpdatePerpetualFeeParamsResponse)(nil), "dydxprotocol.feetiers.MsgUpdatePerpetualFeeParamsResponse")
	proto.RegisterType((*MsgUpdateSpotFeeParams)(nil), "dydxprotocol.feetiers.MsgUpdateSpotFeeParams")
	proto.RegisterType((*MsgUpdateSpotFeeParamsResponse)(nil), "dydxprotocol.feetiers.MsgUpdateSpotFeeParamsResponse")
	proto.RegisterType((*MsgSetMarketFeeDiscountParams)(nil), "dydxprotocol.feetiers.MsgSetMarketFeeDiscountParams")
	proto.RegisterType((*MsgSetMarketFeeDiscountParamsResponse)(nil), "dydxprotocol.feetiers.MsgSetMarketFeeDiscountParamsResponse")
	proto.RegisterType((*MsgSetStakingTiers)(nil), "dydxprotocol.feetiers.MsgSetStakingTiers")
	proto.RegisterType((*MsgSetStakingTiersResponse)(nil), "dydxprotocol.feetiers.MsgSetStakingTiersResponse")
}

func init() { proto.RegisterFile("dydxprotocol/feetiers/tx.proto", fileDescriptor_caa74a3b986b7fd9) }

var fileDescriptor_caa74a3b986b7fd9 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xbf, 0x6f, 0xd3, 0x40,
	0x18, 0xcd, 0xd1, 0xaa, 0x52, 0xaf, 0x94, 0x4a, 0xa6, 0x40, 0x30, 0x60, 0x22, 0x43, 0x45, 0x8a,
	0x14, 0x5b, 0x49, 0x0b, 0x43, 0xc4, 0x42, 0x84, 0xca, 0x14, 0x51, 0x39, 0x65, 0x61, 0xb1, 0x5c,
	0xfb, 0xab, 0x63, 0xb5, 0xf6, 0x59, 0xbe, 0x4b, 0x95, 0x88, 0x8d, 0x91, 0xa9, 0x12, 0x7f, 0x03,
	0x2b, 0x62, 0xe8, 0xc0, 0x9f, 0xd0, 0xb1, 0x62, 0x62, 0x42, 0x28, 0x19, 0xf8, 0x37, 0x50, 0xfc,
	0x2b, 0x0e, 0xf1, 0xb9, 0x84, 0x4c, 0xc9, 0xdd, 0xf7, 0xde, 0xbd, 0xf7, 0xfc, 0x7d, 0x67, 0x63,
	0xc9, 0x1a, 0x58, 0x7d, 0x3f, 0x20, 0x8c, 0x98, 0xe4, 0x44, 0x3d, 0x02, 0x60, 0x0e, 0x04, 0x54,
	0x65, 0x7d, 0x25, 0xdc, 0x14, 0x6e, 0x65, 0xeb, 0x4a, 0x52, 0x17, 0xef, 0x9a, 0x84, 0xba, 0x84,
	0xea, 0x61, 0x45, 0x8d, 0x16, 0x11, 0x43, 0xbc, 0x13, 0xad, 0x54, 0x97, 0xda, 0xea, 0x69, 0x7d,
	0xfc, 0x13, 0x17, 0xe4, 0x7c, 0x29, 0xdf, 0x08, 0x0c, 0x37, 0x21, 0xef, 0x70, 0x30, 0x10, 0xe8,
	0xae, 0x11, 0x1c, 0x03, 0xd3, 0x8f, 0x00, 0x74, 0xcb, 0xa1, 0x26, 0xe9, 0x79, 0x2c, 0x26, 0x55,
	0xf3, 0x49, 0x94, 0x19, 0xc7, 0x8e, 0x67, 0xeb, 0xe3, 0x55, 0x8c, 0xdc, 0xb4, 0x89, 0x4d, 0x22,
	0xcf, 0xe3, 0x7f, 0xd1, 0xae, 0xfc, 0x05, 0xe1, 0x7b, 0x6d, 0x6a, 0xbf, 0xf5, 0x2d, 0x83, 0xc1,
	0x3e, 0x04, 0x3e, 0xb0, 0x9e, 0x71, 0xb2, 0x07, 0xb0, 0x1f, 0x5a, 0x13, 0x9e, 0xe3, 0x55, 0xa3,
	0xc7, 0xba, 0x24, 0x70, 0xd8, 0xa0, 0x8c, 0x2a, 0xa8, 0xba, 0xda, 0x2a, 0x7f, 0x3f, 0xaf, 0x6d,
	0xc6, 0xb1, 0x5f, 0x5a, 0x56, 0x00, 0x94, 0x76, 0x58, 0xe0, 0x78, 0xb6, 0x36, 0x81, 0x0a, 0xaf,
	0xf1, 0x4a, 0x14, 0xae, 0x7c, 0xad, 0x82, 0xaa, 0x6b, 0x8d, 0x6d, 0x25, 0xf7, 0x61, 0x2a, 0xb3,
	0x92, 0xad, 0xe5, 0x8b, 0x9f, 0x0f, 0x4b, 0x5a, 0x4c, 0x6f, 0xde, 0xf8, 0xf0, 0xfb, 0xeb, 0xd3,
	0xc9, 0xc1, 0xf2, 0x16, 0x7e, 0x54, 0xe0, 0x57, 0x03, 0xea, 0x13, 0x8f, 0x82, 0x7c, 0x8e, 0xf0,
	0xed, 0x14, 0xd7, 0xf1, 0x09, 0x5b, 0x3c, 0x92, 0x86, 0x37, 0xa8, 0x4f, 0xa2, 0x2e, 0x4c, 0x65,
	0x7b, 0xcc, 0xc9, 0x36, 0x25, 0x1b, 0xc7, 0x5a, 0xa7, 0xd9, 0xcd, 0x99, 0x74, 0x15, 0x2c, 0xe5,
	0xbb, 0x4e, 0x83, 0x7d, 0x43, 0xf8, 0x41, 0x9b, 0xda, 0x1d, 0x60, 0xed, 0x70, 0x28, 0xf6, 0x00,
	0x5e, 0xc5, 0x23, 0xb1, 0x60, 0xbe, 0x37, 0x99, 0x96, 0x2d, 0x55, 0xd7, 0x1a, 0x75, 0x7e, 0xcb,
	0x38, 0xd2, 0x57, 0xb4, 0xee, 0x09, 0xde, 0x2a, 0x74, 0x9e, 0x66, 0xfc, 0x8c, 0xb0, 0x10, 0x21,
	0x3b, 0xd1, 0x1c, 0x1f, 0x8c, 0x85, 0x17, 0x98, 0xc5, 0xf5, 0xec, 0x7d, 0x48, 0xf2, 0xc9, 0xbc,
	0xb6, 0x4d, 0x34, 0xb5, 0xeb, 0x34, 0x63, 0x60, 0x26, 0xd0, 0x7d, 0x2c, 0xce, 0xda, 0x4c, 0x52,
	0x34, 0x3e, 0x2d, 0xe3, 0xa5, 0x36, 0xb5, 0x85, 0x8f, 0x08, 0x97, 0xb9, 0xf7, 0xab, 0xc1, 0x31,
	0x51, 0x30, 0xe3, 0x62, 0x73, 0x7e, 0x4e, 0x62, 0x4a, 0x78, 0x8f, 0x6f, 0xe6, 0xdd, 0x89, 0xda,
	0x55, 0x47, 0x4e, 0xc1, 0xc5, 0x67, 0x73, 0xc1, 0x53, 0xf1, 0x33, 0x84, 0xc5, 0x82, 0xc1, 0xdd,
	0xe5, 0x9f, 0xca, 0x67, 0x89, 0x2f, 0xfe, 0x87, 0x95, 0x5a, 0x22, 0x78, 0xe3, 0xef, 0x31, 0xdb,
	0x2e, 0x3c, 0x30, 0x0b, 0x15, 0xeb, 0xff, 0x0c, 0x4d, 0x04, 0x5b, 0x07, 0x17, 0x43, 0x09, 0x5d,
	0x0e, 0x25, 0xf4, 0x6b, 0x28, 0xa1, 0xb3, 0x91, 0x54, 0xba, 0x1c, 0x49, 0xa5, 0x1f, 0x23, 0xa9,
	0xf4, 0xae, 0x69, 0x3b, 0xac, 0xdb, 0x3b, 0x54, 0x4c, 0xe2, 0xaa, 0x53, 0x6f, 0xf5, 0xd3, 0xdd,
	0x9a, 0xd9, 0x35, 0x1c, 0x4f, 0x4d, 0x77, 0xfa, 0x99, 0xaf, 0xd5, 0xc0, 0x07, 0x7a, 0xb8, 0x12,
	0x96, 0x76, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x15, 0x38, 0x91, 0xa1, 0xd3, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdatePerpetualFeeParams updates the PerpetualFeeParams in state.
	UpdatePerpetualFeeParams(ctx context.Context, in *MsgUpdatePerpetualFeeParams, opts ...grpc.CallOption) (*MsgUpdatePerpetualFeeParamsResponse, error)
	// UpdateSpotFeeParams updates the SpotFeeParams in state.
	UpdateSpotFeeParams(ctx context.Context, in *MsgUpdateSpotFeeParams, opts ...grpc.CallOption) (*MsgUpdateSpotFeeParamsResponse, error)
	// SetMarketFeeDiscountParams sets or updates PerMarketFeeDiscountParams for
	// specific CLOB pairs.
	SetMarketFeeDiscountParams(ctx context.Context, in *MsgSetMarketFeeDiscountParams, opts ...grpc.CallOption) (*MsgSetMarketFeeDiscountParamsResponse, error)
	// SetStakingTiers sets the staking tiers in state.
	SetStakingTiers(ctx context.Context, in *MsgSetStakingTiers, opts ...grpc.CallOption) (*MsgSetStakingTiersResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdatePerpetualFeeParams(ctx context.Context, in *MsgUpdatePerpetualFeeParams, opts ...grpc.CallOption) (*MsgUpdatePerpetualFeeParamsResponse, error) {
	out := new(MsgUpdatePerpetualFeeParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Msg/UpdatePerpetualFeeParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSpotFeeParams(ctx context.Context, in *MsgUpdateSpotFeeParams, opts ...grpc.CallOption) (*MsgUpdateSpotFeeParamsResponse, error) {
	out := new(MsgUpdateSpotFeeParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Msg/UpdateSpotFeeParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetMarketFeeDiscountParams(ctx context.Context, in *MsgSetMarketFeeDiscountParams, opts ...grpc.CallOption) (*MsgSetMarketFeeDiscountParamsResponse, error) {
	out := new(MsgSetMarketFeeDiscountParamsResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Msg/SetMarketFeeDiscountParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetStakingTiers(ctx context.Context, in *MsgSetStakingTiers, opts ...grpc.CallOption) (*MsgSetStakingTiersResponse, error) {
	out := new(MsgSetStakingTiersResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.feetiers.Msg/SetStakingTiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdatePerpetualFeeParams updates the PerpetualFeeParams in state.
	UpdatePerpetualFeeParams(context.Context, *MsgUpdatePerpetualFeeParams) (*MsgUpdatePerpetualFeeParamsResponse, error)
	// UpdateSpotFeeParams updates the SpotFeeParams in state.
	UpdateSpotFeeParams(context.Context, *MsgUpdateSpotFeeParams) (*MsgUpdateSpotFeeParamsResponse, error)
	// SetMarketFeeDiscountParams sets or updates PerMarketFeeDiscountParams for
	// specific CLOB pairs.
	SetMarketFeeDiscountParams(context.Context, *MsgSetMarketFeeDiscountParams) (*MsgSetMarketFeeDiscountParamsResponse, error)
	// SetStakingTiers sets the staking tiers in state.
	SetStakingTiers(context.Context, *MsgSetStakingTiers) (*MsgSetStakingTiersResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdatePerpetualFeeParams(ctx context.Context, req *MsgUpdatePerpetualFeeParams) (*MsgUpdatePerpetualFeeParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePerpetualFeeParams not implemented")
}
func (*UnimplementedMsgServer) UpdateSpotFeeParams(ctx context.Context, req *MsgUpdateSpotFeeParams) (*MsgUpdateSpotFeeParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpotFeeParams not implemented")
}
func (*UnimplementedMsgServer) SetMarketFeeDiscountParams(ctx context.Context, req *MsgSetMarketFeeDiscountParams) (*MsgSetMarketFeeDiscountParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMarketFeeDiscountParams not implemented")
}
func (*UnimplementedMsgServer) SetStakingTiers(ctx context.Context, req *MsgSetStakingTiers) (*MsgSetStakingTiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStakingTiers not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdatePerpetualFeeParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePerpetualFeeParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePerpetualFeeParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Msg/UpdatePerpetualFeeParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePerpetualFeeParams(ctx, req.(*MsgUpdatePerpetualFeeParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSpotFeeParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateSpotFeeParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSpotFeeParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Msg/UpdateSpotFeeParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSpotFeeParams(ctx, req.(*MsgUpdateSpotFeeParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetMarketFeeDiscountParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetMarketFeeDiscountParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetMarketFeeDiscountParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Msg/SetMarketFeeDiscountParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetMarketFeeDiscountParams(ctx, req.(*MsgSetMarketFeeDiscountParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetStakingTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetStakingTiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetStakingTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.feetiers.Msg/SetStakingTiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetStakingTiers(ctx, req.(*MsgSetStakingTiers))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dydxprotocol.feetiers.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePerpetualFeeParams",
			Handler:    _Msg_UpdatePerpetualFeeParams_Handler,
		},
		{
			MethodName: "UpdateSpotFeeParams",
			Handler:    _Msg_UpdateSpotFeeParams_Handler,
		},
		{
			MethodName: "SetMarketFeeDiscountParams",
			Handler:    _Msg_SetMarketFeeDiscountParams_Handler,
		},
		{
			MethodName: "SetStakingTiers",
			Handler:    _Msg_SetStakingTiers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dydxprotocol/feetiers/tx.proto",
}

func (m *MsgUpdatePerpetualFeeParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePerpetualFeeParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePerpetualFeeParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePerpetualFeeParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePerpetualFeeParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePerpetualFeeParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSpotFeeParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSpotFeeParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSpotFeeParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SpotFeeParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSpotFeeParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSpotFeeParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSpotFeeParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetMarketFeeDiscountParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetMarketFeeDiscountParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetMarketFeeDiscountParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Params) > 0 {
		for iNdEx := len(m.Params) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Params[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetMarketFeeDiscountParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetMarketFeeDiscountParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetMarketFeeDiscountParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetStakingTiers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetStakingTiers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetStakingTiers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StakingTiers) > 0 {
		for iNdEx := len(m.StakingTiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingTiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetStakingTiersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetStakingTiersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetStakingTiersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdatePerpetualFeeParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdatePerpetualFeeParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateSpotFeeParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.SpotFeeParams.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateSpotFeeParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetMarketFeeDiscountParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Params) > 0 {
		for _, e := range m.Params {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSetMarketFeeDiscountParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetStakingTiers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.StakingTiers) > 0 {
		for _, e := range m.StakingTiers {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSetStakingTiersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdatePerpetualFeeParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePerpetualFeeParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePerpetualFeeParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePerpetualFeeParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePerpetualFeeParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePerpetualFeeParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSpotFeeParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSpotFeeParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSpotFeeParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpotFeeParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SpotFeeParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSpotFeeParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSpotFeeParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSpotFeeParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetMarketFeeDiscountParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetMarketFeeDiscountParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetMarketFeeDiscountParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = append(m.Params, PerMarketFeeDiscountParams{})
			if err := m.Params[len(m.Params)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetMarketFeeDiscountParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetMarketFeeDiscountParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetMarketFeeDiscountParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetStakingTiers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetStakingTiers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetStakingTiers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingTiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingTiers = append(m.StakingTiers, &StakingTier{})
			if err := m.StakingTiers[len(m.StakingTiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetStakingTiersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetStakingTiersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetStakingTiersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
