// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/subaccounts/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the subaccounts module's genesis state.
type GenesisState struct {
	Subaccounts []Subaccount `protobuf:"bytes,1,rep,name=subaccounts,proto3" json:"subaccounts"`
	// Explicit owner/type mappings for persisted FUNDING and SPOT accounts.
	TypedSubaccounts []TypedSubaccount `protobuf:"bytes,2,rep,name=typed_subaccounts,json=typedSubaccounts,proto3" json:"typed_subaccounts"`
	// Next monotonic business subaccount number for each owner.
	BusinessNumberCursors []BusinessSubaccountNumberCursor `protobuf:"bytes,3,rep,name=business_number_cursors,json=businessNumberCursors,proto3" json:"business_number_cursors"`
	// Persisted short-term order epochs for SPOT payment assets.
	SpotOrderEpochs []SpotOrderEpoch `protobuf:"bytes,4,rep,name=spot_order_epochs,json=spotOrderEpochs,proto3" json:"spot_order_epochs"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_82521a0c7c1b8867, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetSubaccounts() []Subaccount {
	if m != nil {
		return m.Subaccounts
	}
	return nil
}

func (m *GenesisState) GetTypedSubaccounts() []TypedSubaccount {
	if m != nil {
		return m.TypedSubaccounts
	}
	return nil
}

func (m *GenesisState) GetBusinessNumberCursors() []BusinessSubaccountNumberCursor {
	if m != nil {
		return m.BusinessNumberCursors
	}
	return nil
}

func (m *GenesisState) GetSpotOrderEpochs() []SpotOrderEpoch {
	if m != nil {
		return m.SpotOrderEpochs
	}
	return nil
}

// TypedSubaccount records the unique owner/type mapping.
type TypedSubaccount struct {
	Owner        string        `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	AccountType  AccountType   `protobuf:"varint,2,opt,name=account_type,json=accountType,proto3,enum=dydxprotocol.subaccounts.AccountType" json:"account_type,omitempty"`
	SubaccountId *SubaccountId `protobuf:"bytes,3,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
}

func (m *TypedSubaccount) Reset()         { *m = TypedSubaccount{} }
func (m *TypedSubaccount) String() string { return proto.CompactTextString(m) }
func (*TypedSubaccount) ProtoMessage()    {}
func (*TypedSubaccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_82521a0c7c1b8867, []int{1}
}
func (m *TypedSubaccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TypedSubaccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TypedSubaccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TypedSubaccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypedSubaccount.Merge(m, src)
}
func (m *TypedSubaccount) XXX_Size() int {
	return m.Size()
}
func (m *TypedSubaccount) XXX_DiscardUnknown() {
	xxx_messageInfo_TypedSubaccount.DiscardUnknown(m)
}

var xxx_messageInfo_TypedSubaccount proto.InternalMessageInfo

func (m *TypedSubaccount) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TypedSubaccount) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (m *TypedSubaccount) GetSubaccountId() *SubaccountId {
	if m != nil {
		return m.SubaccountId
	}
	return nil
}

// BusinessSubaccountNumberCursor records the next number to allocate.
type BusinessSubaccountNumberCursor struct {
	Owner      string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	NextNumber uint32 `protobuf:"varint,2,opt,name=next_number,json=nextNumber,proto3" json:"next_number,omitempty"`
}

func (m *BusinessSubaccountNumberCursor) Reset()         { *m = BusinessSubaccountNumberCursor{} }
func (m *BusinessSubaccountNumberCursor) String() string { return proto.CompactTextString(m) }
func (*BusinessSubaccountNumberCursor) ProtoMessage()    {}
func (*BusinessSubaccountNumberCursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_82521a0c7c1b8867, []int{2}
}
func (m *BusinessSubaccountNumberCursor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BusinessSubaccountNumberCursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BusinessSubaccountNumberCursor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BusinessSubaccountNumberCursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessSubaccountNumberCursor.Merge(m, src)
}
func (m *BusinessSubaccountNumberCursor) XXX_Size() int {
	return m.Size()
}
func (m *BusinessSubaccountNumberCursor) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessSubaccountNumberCursor.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessSubaccountNumberCursor proto.InternalMessageInfo

func (m *BusinessSubaccountNumberCursor) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *BusinessSubaccountNumberCursor) GetNextNumber() uint32 {
	if m != nil {
		return m.NextNumber
	}
	return 0
}

// SpotOrderEpoch records the current signed-order version for a SPOT asset.
type SpotOrderEpoch struct {
	SubaccountId *SubaccountId `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id,omitempty"`
	AssetId      uint32        `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Epoch        uint64        `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *SpotOrderEpoch) Reset()         { *m = SpotOrderEpoch{} }
func (m *SpotOrderEpoch) String() string { return proto.CompactTextString(m) }
func (*SpotOrderEpoch) ProtoMessage()    {}
func (*SpotOrderEpoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_82521a0c7c1b8867, []int{3}
}
func (m *SpotOrderEpoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpotOrderEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpotOrderEpoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpotOrderEpoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotOrderEpoch.Merge(m, src)
}
func (m *SpotOrderEpoch) XXX_Size() int {
	return m.Size()
}
func (m *SpotOrderEpoch) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotOrderEpoch.DiscardUnknown(m)
}

var xxx_messageInfo_SpotOrderEpoch proto.InternalMessageInfo

func (m *SpotOrderEpoch) GetSubaccountId() *SubaccountId {
	if m != nil {
		return m.SubaccountId
	}
	return nil
}

func (m *SpotOrderEpoch) GetAssetId() uint32 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *SpotOrderEpoch) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "dydxprotocol.subaccounts.GenesisState")
	proto.RegisterType((*TypedSubaccount)(nil), "dydxprotocol.subaccounts.TypedSubaccount")
	proto.RegisterType((*BusinessSubaccountNumberCursor)(nil), "dydxprotocol.subaccounts.BusinessSubaccountNumberCursor")
	proto.RegisterType((*SpotOrderEpoch)(nil), "dydxprotocol.subaccounts.SpotOrderEpoch")
}

func init() {
	proto.RegisterFile("dydxprotocol/subaccounts/genesis.proto", fileDescriptor_82521a0c7c1b8867)
}

var fileDescriptor_82521a0c7c1b8867 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6b, 0xd4, 0x40,
	0x18, 0xde, 0xe9, 0x6e, 0xfd, 0x98, 0xdd, 0xb6, 0x76, 0x58, 0x31, 0xed, 0x21, 0x5d, 0x16, 0x2d,
	0xe9, 0xa1, 0x09, 0xac, 0x1e, 0xbc, 0x78, 0xe8, 0x8a, 0x68, 0x51, 0x14, 0x52, 0x41, 0x28, 0x42,
	0x48, 0x32, 0x43, 0x36, 0xe0, 0x66, 0xe2, 0xbc, 0x93, 0xba, 0xfd, 0x13, 0xc5, 0x1f, 0xe3, 0x8f,
	0xe8, 0xb1, 0x78, 0xea, 0x49, 0x64, 0xf7, 0x8f, 0xc8, 0xcc, 0xc4, 0x6e, 0x62, 0x49, 0x51, 0x6f,
	0xef, 0xd7, 0xf3, 0x3c, 0xf3, 0xbc, 0x33, 0x83, 0x77, 0xe9, 0x29, 0x9d, 0xe5, 0x82, 0x4b, 0x1e,
	0xf3, 0x4f, 0x1e, 0x14, 0x51, 0x18, 0xc7, 0xbc, 0xc8, 0x24, 0x78, 0x09, 0xcb, 0x18, 0xa4, 0xe0,
	0xea, 0x26, 0xb1, 0xaa, 0x73, 0x6e, 0x65, 0x6e, 0xbb, 0x9f, 0xf0, 0x84, 0xeb, 0x8e, 0xa7, 0x22,
	0x33, 0xbf, 0xbd, 0x15, 0x73, 0x98, 0x72, 0x08, 0x4c, 0xc3, 0x24, 0x65, 0x6b, 0xaf, 0x51, 0x72,
	0x19, 0x9b, 0xd1, 0xe1, 0x59, 0x1b, 0xf7, 0x5e, 0x9a, 0x73, 0x1c, 0xc9, 0x50, 0x32, 0xf2, 0x06,
	0x77, 0x2b, 0x00, 0x0b, 0x0d, 0xda, 0x4e, 0x77, 0xf4, 0xd0, 0x6d, 0x3a, 0x9c, 0x7b, 0x74, 0x15,
	0x8f, 0x3b, 0xe7, 0x3f, 0x76, 0x5a, 0x7e, 0x15, 0x4e, 0x3e, 0xe2, 0x4d, 0x79, 0x9a, 0x33, 0x1a,
	0x54, 0x39, 0x57, 0x34, 0xe7, 0x5e, 0x33, 0xe7, 0x7b, 0x05, 0xb9, 0x46, 0x7c, 0x4f, 0xd6, 0xcb,
	0x40, 0x4e, 0xf0, 0x83, 0xa8, 0x80, 0x34, 0x63, 0x00, 0x41, 0x56, 0x4c, 0x23, 0x26, 0x82, 0xb8,
	0x10, 0xc0, 0x05, 0x58, 0x6d, 0xad, 0xf1, 0xb4, 0x59, 0x63, 0x5c, 0x02, 0x97, 0x7c, 0x6f, 0x35,
	0xc3, 0x73, 0x4d, 0x50, 0x4a, 0xde, 0xff, 0x4d, 0x5f, 0xed, 0x01, 0x39, 0xc6, 0x9b, 0x90, 0x73,
	0x19, 0x70, 0x41, 0x99, 0x08, 0x58, 0xce, 0xe3, 0x09, 0x58, 0x1d, 0xad, 0xe8, 0xdc, 0xb0, 0xa9,
	0x9c, 0xcb, 0x77, 0x0a, 0xf1, 0x42, 0x01, 0x4a, 0x85, 0x0d, 0xa8, 0x55, 0x61, 0x78, 0x89, 0xf0,
	0xc6, 0x1f, 0xfe, 0x89, 0x8b, 0x57, 0xf9, 0x97, 0x8c, 0x09, 0x0b, 0x0d, 0x90, 0x73, 0x77, 0x6c,
	0x7d, 0xff, 0xb6, 0xdf, 0x2f, 0x2f, 0xfc, 0x80, 0x52, 0xa1, 0x5c, 0x48, 0x91, 0x66, 0x89, 0x6f,
	0xc6, 0xc8, 0x2b, 0xdc, 0x2b, 0xa1, 0x81, 0xda, 0x99, 0xb5, 0x32, 0x40, 0xce, 0xfa, 0xe8, 0x51,
	0xf3, 0xd1, 0x0e, 0x4c, 0xa0, 0x74, 0xfd, 0x6e, 0xb8, 0x4c, 0xc8, 0x6b, 0xbc, 0xb6, 0x9c, 0x0b,
	0x52, 0x6a, 0xb5, 0x07, 0xc8, 0xe9, 0x8e, 0x76, 0xff, 0xe6, 0x3d, 0x1c, 0x52, 0xbf, 0x07, 0x95,
	0x6c, 0xf8, 0x19, 0xdb, 0x37, 0x6f, 0xfd, 0x9f, 0x8d, 0xee, 0xe0, 0x6e, 0xc6, 0x66, 0xb2, 0xbc,
	0x7c, 0xed, 0x73, 0xcd, 0xc7, 0xaa, 0x64, 0x68, 0x87, 0x67, 0x08, 0xaf, 0xd7, 0xf7, 0x7e, 0xdd,
	0x12, 0xfa, 0x7f, 0x4b, 0x64, 0x0b, 0xdf, 0x09, 0x01, 0x98, 0xe6, 0x31, 0xea, 0xb7, 0x75, 0x7e,
	0x48, 0x49, 0x1f, 0xaf, 0xea, 0x97, 0xa1, 0x57, 0xd6, 0xf1, 0x4d, 0x32, 0xfe, 0x70, 0x3e, 0xb7,
	0xd1, 0xc5, 0xdc, 0x46, 0x3f, 0xe7, 0x36, 0xfa, 0xba, 0xb0, 0x5b, 0x17, 0x0b, 0xbb, 0x75, 0xb9,
	0xb0, 0x5b, 0xc7, 0xcf, 0x92, 0x54, 0x4e, 0x8a, 0xc8, 0x8d, 0xf9, 0xd4, 0xab, 0xfd, 0xdf, 0x93,
	0x27, 0xfb, 0xf1, 0x24, 0x4c, 0x33, 0xef, 0xaa, 0x32, 0xab, 0xfd, 0x69, 0x75, 0xc5, 0x10, 0xdd,
	0xd2, 0xdd, 0xc7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0x57, 0x90, 0xc3, 0x6f, 0x04, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SpotOrderEpochs) > 0 {
		for iNdEx := len(m.SpotOrderEpochs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SpotOrderEpochs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.BusinessNumberCursors) > 0 {
		for iNdEx := len(m.BusinessNumberCursors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BusinessNumberCursors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TypedSubaccounts) > 0 {
		for iNdEx := len(m.TypedSubaccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TypedSubaccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Subaccounts) > 0 {
		for iNdEx := len(m.Subaccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Subaccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *TypedSubaccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TypedSubaccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TypedSubaccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubaccountId != nil {
		{
			size, err := m.SubaccountId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.AccountType != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AccountType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BusinessSubaccountNumberCursor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BusinessSubaccountNumberCursor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BusinessSubaccountNumberCursor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextNumber != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextNumber))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SpotOrderEpoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpotOrderEpoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpotOrderEpoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	if m.AssetId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x10
	}
	if m.SubaccountId != nil {
		{
			size, err := m.SubaccountId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Subaccounts) > 0 {
		for _, e := range m.Subaccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TypedSubaccounts) > 0 {
		for _, e := range m.TypedSubaccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BusinessNumberCursors) > 0 {
		for _, e := range m.BusinessNumberCursors {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SpotOrderEpochs) > 0 {
		for _, e := range m.SpotOrderEpochs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *TypedSubaccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.AccountType != 0 {
		n += 1 + sovGenesis(uint64(m.AccountType))
	}
	if m.SubaccountId != nil {
		l = m.SubaccountId.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *BusinessSubaccountNumberCursor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.NextNumber != 0 {
		n += 1 + sovGenesis(uint64(m.NextNumber))
	}
	return n
}

func (m *SpotOrderEpoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubaccountId != nil {
		l = m.SubaccountId.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.AssetId != 0 {
		n += 1 + sovGenesis(uint64(m.AssetId))
	}
	if m.Epoch != 0 {
		n += 1 + sovGenesis(uint64(m.Epoch))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subaccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subaccounts = append(m.Subaccounts, Subaccount{})
			if err := m.Subaccounts[len(m.Subaccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypedSubaccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypedSubaccounts = append(m.TypedSubaccounts, TypedSubaccount{})
			if err := m.TypedSubaccounts[len(m.TypedSubaccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessNumberCursors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessNumberCursors = append(m.BusinessNumberCursors, BusinessSubaccountNumberCursor{})
			if err := m.BusinessNumberCursors[len(m.BusinessNumberCursors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpotOrderEpochs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpotOrderEpochs = append(m.SpotOrderEpochs, SpotOrderEpoch{})
			if err := m.SpotOrderEpochs[len(m.SpotOrderEpochs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TypedSubaccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TypedSubaccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TypedSubaccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountType", wireType)
			}
			m.AccountType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountType |= AccountType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SubaccountId == nil {
				m.SubaccountId = &SubaccountId{}
			}
			if err := m.SubaccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BusinessSubaccountNumberCursor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BusinessSubaccountNumberCursor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BusinessSubaccountNumberCursor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextNumber", wireType)
			}
			m.NextNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextNumber |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpotOrderEpoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpotOrderEpoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpotOrderEpoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SubaccountId == nil {
				m.SubaccountId = &SubaccountId{}
			}
			if err := m.SubaccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
