// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/clob/spot_resource_params.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SpotResourceParams defines consensus limits for spot order lifecycle work.
type SpotResourceParams struct {
	// Maximum active spot long-term orders owned by one subaccount.
	MaxSpotStatefulOrdersPerSubaccount uint32 `protobuf:"varint,1,opt,name=max_spot_stateful_orders_per_subaccount,json=maxSpotStatefulOrdersPerSubaccount,proto3" json:"max_spot_stateful_orders_per_subaccount,omitempty"`
	// Maximum spot orders released by the delisting scheduler per block.
	MaxSpotDelistOrdersPerBlock uint32 `protobuf:"varint,2,opt,name=max_spot_delist_orders_per_block,json=maxSpotDelistOrdersPerBlock,proto3" json:"max_spot_delist_orders_per_block,omitempty"`
}

func (m *SpotResourceParams) Reset()         { *m = SpotResourceParams{} }
func (m *SpotResourceParams) String() string { return proto.CompactTextString(m) }
func (*SpotResourceParams) ProtoMessage()    {}
func (*SpotResourceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff479e3f5321e26, []int{0}
}
func (m *SpotResourceParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpotResourceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpotResourceParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpotResourceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotResourceParams.Merge(m, src)
}
func (m *SpotResourceParams) XXX_Size() int {
	return m.Size()
}
func (m *SpotResourceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotResourceParams.DiscardUnknown(m)
}

var xxx_messageInfo_SpotResourceParams proto.InternalMessageInfo

func (m *SpotResourceParams) GetMaxSpotStatefulOrdersPerSubaccount() uint32 {
	if m != nil {
		return m.MaxSpotStatefulOrdersPerSubaccount
	}
	return 0
}

func (m *SpotResourceParams) GetMaxSpotDelistOrdersPerBlock() uint32 {
	if m != nil {
		return m.MaxSpotDelistOrdersPerBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*SpotResourceParams)(nil), "dydxprotocol.clob.SpotResourceParams")
}

func init() {
	proto.RegisterFile("dydxprotocol/clob/spot_resource_params.proto", fileDescriptor_1ff479e3f5321e26)
}

var fileDescriptor_1ff479e3f5321e26 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0xc6, 0xf1, 0x98, 0x81, 0x21, 0x12, 0x03, 0x99, 0x2a, 0x21, 0x59, 0x55, 0x17, 0x18, 0x20,
	0x19, 0x40, 0x1c, 0xa0, 0x82, 0x99, 0xa8, 0xd9, 0x58, 0x2c, 0xdb, 0x31, 0x34, 0xc2, 0xe9, 0xb3,
	0xfc, 0x9e, 0x51, 0x7a, 0x0b, 0x8e, 0xc2, 0x31, 0x18, 0x3b, 0x32, 0xa2, 0xe4, 0x22, 0x28, 0x26,
	0x8a, 0xca, 0xfa, 0xf4, 0x7b, 0xff, 0xe1, 0x4b, 0xaf, 0xeb, 0x7d, 0xdd, 0x39, 0x0f, 0x04, 0x1a,
	0x6c, 0xa1, 0x2d, 0xa8, 0x02, 0x1d, 0x90, 0xf0, 0x06, 0x21, 0x78, 0x6d, 0x84, 0x93, 0x5e, 0xb6,
	0x98, 0x47, 0x92, 0x9d, 0x1f, 0xeb, 0x7c, 0xd4, 0xab, 0x4f, 0x96, 0x66, 0x95, 0x03, 0xda, 0x4c,
	0x0f, 0x65, 0xf4, 0x59, 0x95, 0x5e, 0xb6, 0xb2, 0x13, 0xb1, 0x85, 0x24, 0xc9, 0xbc, 0x04, 0x2b,
	0xc0, 0xd7, 0xc6, 0xa3, 0x70, 0xc6, 0x0b, 0x0c, 0x4a, 0x6a, 0x0d, 0x61, 0x47, 0x0b, 0xb6, 0x64,
	0x57, 0x67, 0x9b, 0x55, 0x2b, 0xbb, 0xb1, 0x53, 0x4d, 0xf8, 0x29, 0xda, 0xd2, 0xf8, 0x6a, 0x96,
	0xd9, 0x63, 0xba, 0x9c, 0xa3, 0xb5, 0xb1, 0x0d, 0xd2, 0x71, 0x52, 0x59, 0xd0, 0x6f, 0x8b, 0x93,
	0x58, 0xbb, 0x98, 0x6a, 0x0f, 0x51, 0xcd, 0xad, 0xf5, 0x48, 0xd6, 0xe5, 0x57, 0xcf, 0xd9, 0xa1,
	0xe7, 0xec, 0xa7, 0xe7, 0xec, 0x63, 0xe0, 0xc9, 0x61, 0xe0, 0xc9, 0xf7, 0xc0, 0x93, 0xe7, 0xfb,
	0xd7, 0x86, 0xb6, 0x41, 0xe5, 0x1a, 0xda, 0xe2, 0xdf, 0x30, 0xef, 0x77, 0x37, 0x7a, 0x2b, 0x9b,
	0x5d, 0x31, 0x5f, 0xba, 0xbf, 0xb1, 0x68, 0xef, 0x0c, 0xaa, 0xd3, 0x78, 0xbe, 0xfd, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xb6, 0xfd, 0x0e, 0x77, 0x4e, 0x01, 0x00, 0x00,
}

func (m *SpotResourceParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpotResourceParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpotResourceParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxSpotDelistOrdersPerBlock != 0 {
		i = encodeVarintSpotResourceParams(dAtA, i, uint64(m.MaxSpotDelistOrdersPerBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxSpotStatefulOrdersPerSubaccount != 0 {
		i = encodeVarintSpotResourceParams(dAtA, i, uint64(m.MaxSpotStatefulOrdersPerSubaccount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSpotResourceParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovSpotResourceParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SpotResourceParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxSpotStatefulOrdersPerSubaccount != 0 {
		n += 1 + sovSpotResourceParams(uint64(m.MaxSpotStatefulOrdersPerSubaccount))
	}
	if m.MaxSpotDelistOrdersPerBlock != 0 {
		n += 1 + sovSpotResourceParams(uint64(m.MaxSpotDelistOrdersPerBlock))
	}
	return n
}

func sovSpotResourceParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSpotResourceParams(x uint64) (n int) {
	return sovSpotResourceParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SpotResourceParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpotResourceParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpotResourceParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpotResourceParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSpotStatefulOrdersPerSubaccount", wireType)
			}
			m.MaxSpotStatefulOrdersPerSubaccount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpotResourceParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSpotStatefulOrdersPerSubaccount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSpotDelistOrdersPerBlock", wireType)
			}
			m.MaxSpotDelistOrdersPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpotResourceParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSpotDelistOrdersPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpotResourceParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpotResourceParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSpotResourceParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSpotResourceParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpotResourceParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpotResourceParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSpotResourceParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSpotResourceParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSpotResourceParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSpotResourceParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSpotResourceParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSpotResourceParams = fmt.Errorf("proto: unexpected end of group")
)
