// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/clob/stateful_spot_reservation.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_dydxprotocol_v4_chain_protocol_dtypes "github.com/dydxprotocol/v4-chain/protocol/dtypes"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// StatefulSpotReservation records the asset locked by one spot long-term order.
type StatefulSpotReservation struct {
	// OrderId identifies the stateful spot order that owns this reservation.
	OrderId OrderId `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	// OutgoingAssetId identifies the asset whose available balance is reduced.
	OutgoingAssetId uint32 `protobuf:"varint,2,opt,name=outgoing_asset_id,json=outgoingAssetId,proto3" json:"outgoing_asset_id,omitempty"`
	// ReservedQuantums is the remaining amount locked for this order.
	ReservedQuantums github_com_dydxprotocol_v4_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,3,opt,name=reserved_quantums,json=reservedQuantums,proto3,customtype=github.com/dydxprotocol/v4-chain/protocol/dtypes.SerializableInt" json:"reserved_quantums"`
	// RemainingBaseQuantums is the unfilled base quantity used for recalculation.
	RemainingBaseQuantums uint64 `protobuf:"varint,4,opt,name=remaining_base_quantums,json=remainingBaseQuantums,proto3" json:"remaining_base_quantums,omitempty"`
}

func (m *StatefulSpotReservation) Reset()         { *m = StatefulSpotReservation{} }
func (m *StatefulSpotReservation) String() string { return proto.CompactTextString(m) }
func (*StatefulSpotReservation) ProtoMessage()    {}
func (*StatefulSpotReservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_803c90248d14fa0a, []int{0}
}
func (m *StatefulSpotReservation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatefulSpotReservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatefulSpotReservation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatefulSpotReservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatefulSpotReservation.Merge(m, src)
}
func (m *StatefulSpotReservation) XXX_Size() int {
	return m.Size()
}
func (m *StatefulSpotReservation) XXX_DiscardUnknown() {
	xxx_messageInfo_StatefulSpotReservation.DiscardUnknown(m)
}

var xxx_messageInfo_StatefulSpotReservation proto.InternalMessageInfo

func (m *StatefulSpotReservation) GetOrderId() OrderId {
	if m != nil {
		return m.OrderId
	}
	return OrderId{}
}

func (m *StatefulSpotReservation) GetOutgoingAssetId() uint32 {
	if m != nil {
		return m.OutgoingAssetId
	}
	return 0
}

func (m *StatefulSpotReservation) GetRemainingBaseQuantums() uint64 {
	if m != nil {
		return m.RemainingBaseQuantums
	}
	return 0
}

func init() {
	proto.RegisterType((*StatefulSpotReservation)(nil), "dydxprotocol.clob.StatefulSpotReservation")
}

func init() {
	proto.RegisterFile("dydxprotocol/clob/stateful_spot_reservation.proto", fileDescriptor_803c90248d14fa0a)
}

var fileDescriptor_803c90248d14fa0a = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x33, 0xfd, 0x97, 0xbf, 0x12, 0x15, 0x6d, 0x50, 0x5a, 0x0a, 0xa6, 0xc1, 0x55, 0x10,
	0x4c, 0xf0, 0x83, 0x6e, 0xdc, 0x68, 0x56, 0x76, 0xa5, 0xa6, 0x3b, 0x37, 0x61, 0x92, 0x19, 0xd3,
	0x81, 0x34, 0x37, 0xce, 0x4c, 0x4a, 0xeb, 0x53, 0xf8, 0x2a, 0xbe, 0x45, 0x97, 0x5d, 0x8a, 0x8b,
	0x22, 0xed, 0x8b, 0xc8, 0x24, 0xfd, 0x50, 0xba, 0x71, 0x97, 0x9c, 0x7b, 0xee, 0xf9, 0x9d, 0xcb,
	0xe8, 0xe7, 0x64, 0x44, 0x86, 0x19, 0x07, 0x09, 0x11, 0x24, 0x6e, 0x94, 0x40, 0xe8, 0x0a, 0x89,
	0x25, 0x7d, 0xce, 0x93, 0x40, 0x64, 0x20, 0x03, 0x4e, 0x05, 0xe5, 0x03, 0x2c, 0x19, 0xa4, 0x4e,
	0xe1, 0x33, 0x6a, 0x3f, 0x57, 0x1c, 0xb5, 0xd2, 0x3c, 0x8c, 0x21, 0x86, 0x42, 0x72, 0xd5, 0x57,
	0x69, 0x6c, 0x1e, 0x6f, 0x66, 0x03, 0x27, 0x94, 0x97, 0xe3, 0x93, 0xf7, 0x8a, 0x5e, 0xef, 0x2e,
	0x58, 0xdd, 0x0c, 0xa4, 0xbf, 0x26, 0x19, 0xd7, 0xfa, 0x76, 0x61, 0x0d, 0x18, 0x69, 0x20, 0x0b,
	0xd9, 0x3b, 0x17, 0x4d, 0x67, 0x03, 0xeb, 0xdc, 0x2b, 0x4b, 0x87, 0x78, 0xd5, 0xf1, 0xb4, 0xa5,
	0xf9, 0x5b, 0x50, 0xfe, 0x1a, 0xa7, 0x7a, 0x0d, 0x72, 0x19, 0x03, 0x4b, 0xe3, 0x00, 0x0b, 0x41,
	0xa5, 0x4a, 0xa9, 0x58, 0xc8, 0xde, 0xf3, 0xf7, 0x97, 0x83, 0x5b, 0xa5, 0x77, 0x88, 0x91, 0xeb,
	0xb5, 0xf2, 0x42, 0x4a, 0x82, 0x97, 0x1c, 0xa7, 0x32, 0xef, 0x8b, 0xc6, 0x3f, 0x0b, 0xd9, 0xbb,
	0xde, 0x9d, 0x4a, 0xfd, 0x9c, 0xb6, 0x6e, 0x62, 0x26, 0x7b, 0x79, 0xe8, 0x44, 0xd0, 0x77, 0x7f,
	0x5d, 0x34, 0xb8, 0x3a, 0x8b, 0x7a, 0x98, 0xa5, 0xee, 0x4a, 0x21, 0x72, 0x94, 0x51, 0xe1, 0x74,
	0x29, 0x67, 0x38, 0x61, 0xaf, 0x38, 0x4c, 0x68, 0x27, 0x95, 0xfe, 0xc1, 0x12, 0xf1, 0xb8, 0x20,
	0x18, 0x6d, 0xbd, 0xce, 0x69, 0x1f, 0xb3, 0x54, 0x75, 0x0c, 0xb1, 0xa0, 0x6b, 0x78, 0xd5, 0x42,
	0x76, 0xd5, 0x3f, 0x5a, 0x8d, 0x3d, 0x2c, 0xe8, 0x72, 0xcf, 0x7b, 0x18, 0xcf, 0x4c, 0x34, 0x99,
	0x99, 0xe8, 0x6b, 0x66, 0xa2, 0xb7, 0xb9, 0xa9, 0x4d, 0xe6, 0xa6, 0xf6, 0x31, 0x37, 0xb5, 0xa7,
	0xf6, 0xdf, 0x5b, 0x0e, 0xcb, 0xb7, 0x28, 0xba, 0x86, 0xff, 0x0b, 0xf9, 0xf2, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0x6d, 0xde, 0x29, 0x09, 0x02, 0x00, 0x00,
}

func (m *StatefulSpotReservation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatefulSpotReservation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatefulSpotReservation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemainingBaseQuantums != 0 {
		i = encodeVarintStatefulSpotReservation(dAtA, i, uint64(m.RemainingBaseQuantums))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.ReservedQuantums.Size()
		i -= size
		if _, err := m.ReservedQuantums.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStatefulSpotReservation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.OutgoingAssetId != 0 {
		i = encodeVarintStatefulSpotReservation(dAtA, i, uint64(m.OutgoingAssetId))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.OrderId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStatefulSpotReservation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintStatefulSpotReservation(dAtA []byte, offset int, v uint64) int {
	offset -= sovStatefulSpotReservation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StatefulSpotReservation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.OrderId.Size()
	n += 1 + l + sovStatefulSpotReservation(uint64(l))
	if m.OutgoingAssetId != 0 {
		n += 1 + sovStatefulSpotReservation(uint64(m.OutgoingAssetId))
	}
	l = m.ReservedQuantums.Size()
	n += 1 + l + sovStatefulSpotReservation(uint64(l))
	if m.RemainingBaseQuantums != 0 {
		n += 1 + sovStatefulSpotReservation(uint64(m.RemainingBaseQuantums))
	}
	return n
}

func sovStatefulSpotReservation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStatefulSpotReservation(x uint64) (n int) {
	return sovStatefulSpotReservation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StatefulSpotReservation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatefulSpotReservation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatefulSpotReservation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatefulSpotReservation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatefulSpotReservation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStatefulSpotReservation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStatefulSpotReservation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OrderId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutgoingAssetId", wireType)
			}
			m.OutgoingAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatefulSpotReservation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutgoingAssetId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedQuantums", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatefulSpotReservation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStatefulSpotReservation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStatefulSpotReservation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReservedQuantums.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingBaseQuantums", wireType)
			}
			m.RemainingBaseQuantums = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatefulSpotReservation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingBaseQuantums |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStatefulSpotReservation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatefulSpotReservation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStatefulSpotReservation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStatefulSpotReservation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatefulSpotReservation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatefulSpotReservation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStatefulSpotReservation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStatefulSpotReservation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStatefulSpotReservation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStatefulSpotReservation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStatefulSpotReservation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStatefulSpotReservation = fmt.Errorf("proto: unexpected end of group")
)
